### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by qiaohhgz** [apache/dubbo-spring-boot-project#127]
java.lang.NoClassDefFoundError: org/I0Itec/zkclient/IZkStateListener

**Comment by qiaohhgz** [comment]
<dependency>
            <groupId>com.101tec</groupId>
            <artifactId>zkclient</artifactId>
            <version>0.7</version>
        </dependency>

**Comment by guixincui** [comment]
java.lang.NoClassDefFoundError: org/I0Itec/zkclient/IZkStateListener
	at java.lang.ClassLoader.defineClass1(Native Method) ~[na:1.8.0_144]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[na:1.8.0_144]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[na:1.8.0_144]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) ~[na:1.8.0_144]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[na:1.8.0_144]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368) ~[na:1.8.0_144]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[na:1.8.0_144]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_144]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361) ~[na:1.8.0_144]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_144]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335) ~[na:1.8.0_144]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_144]
	at com.alibaba.dubbo.remoting.zookeeper.zkclient.ZkclientZookeeperClient.<init>(ZkclientZookeeperClient.java:41) ~[dubbo-2.5.10.jar:2.0.1]
	at com.alibaba.dubbo.remoting.zookeeper.zkclient.ZkclientZookeeperTransporter.connect(ZkclientZookeeperTransporter.java:26) ~[dubbo-2.5.10.jar:2.0.1]
	at com.alibaba.dubbo.remoting.zookeeper.ZookeeperTransporter$Adaptive.connect(ZookeeperTransporter$Adaptive.java) ~[dubbo-2.5.10.jar:2.0.1]
	at com.alibaba.dubbo.registry.zookeeper.ZookeeperRegistry.<init>(ZookeeperRegistry.java:69) ~[dubbo-2.5.10.jar:2.0.1]
	at com.alibaba.dubbo.registry.zookeeper.ZookeeperRegistryFactory.createRegistry(ZookeeperRegistryFactory.java:37) ~[dubbo-2.5.10.jar:2.0.1]
	at com.alibaba.dubbo.registry.support.AbstractRegistryFactory.getRegistry(AbstractRegistryFactory.java:95) ~[dubbo-2.5.10.jar:2.0.1]
	at com.alibaba.dubbo.registry.RegistryFactory$Adaptive.getRegistry(RegistryFactory$Adaptive.java) ~[dubbo-2.5.10.jar:2.0.1]
	at com.alibaba.dubbo.registry.integration.RegistryProtocol.getRegistry(RegistryProtocol.java:200) ~[dubbo-2.5.10.jar:2.0.1]
	at com.alibaba.dubbo.registry.integration.RegistryProtocol.export(RegistryProtocol.java:134) ~[dubbo-2.5.10.jar:2.0.1]
	at com.alibaba.dubbo.rpc.protocol.ProtocolListenerWrapper.export(ProtocolListenerWrapper.java:54) ~[dubbo-2.5.10.jar:2.0.1]
	at com.alibaba.dubbo.qos.protocol.QosProtocolWrapper.export(QosProtocolWrapper.java:54) ~[dubbo-2.5.10.jar:2.0.1]
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper.export(ProtocolFilterWrapper.java:91) ~[dubbo-2.5.10.jar:2.0.1]
	at com.alibaba.dubbo.rpc.Protocol$Adaptive.export(Protocol$Adaptive.java) ~[dubbo-2.5.10.jar:2.0.1]
	at com.alibaba.dubbo.config.ServiceConfig.doExportUrlsFor1Protocol(ServiceConfig.java:504) ~[dubbo-2.5.10.jar:2.0.1]
	at com.alibaba.dubbo.config.ServiceConfig.doExportUrls(ServiceConfig.java:356) ~[dubbo-2.5.10.jar:2.0.1]
	at com.alibaba.dubbo.config.ServiceConfig.doExport(ServiceConfig.java:315) ~[dubbo-2.5.10.jar:2.0.1]
	at com.alibaba.dubbo.config.ServiceConfig.export(ServiceConfig.java:214) ~[dubbo-2.5.10.jar:2.0.1]
	at com.alibaba.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:120) ~[dubbo-2.5.10.jar:2.0.1]
	at com.alibaba.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:49) ~[dubbo-2.5.10.jar:2.0.1]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:163) ~[spring-context-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:136) ~[spring-context-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:380) ~[spring-context-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:334) ~[spring-context-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:854) ~[spring-context-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:140) ~[spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:540) ~[spring-context-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118) ~[spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:752) [spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.doRun(SpringApplication.java:347) [spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:295) [spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1112) [spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1101) [spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at com.alibaba.boot.dubbo.demo.provider.DubboProviderDemo.main(DubboProviderDemo.java:10) [classes/:na]
Caused by: java.lang.ClassNotFoundException: org.I0Itec.zkclient.IZkStateListener
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_144]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_144]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335) ~[na:1.8.0_144]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_144]
	... 45 common frames omitted
