### ISSUE TITLE
配置dubbo.provider.delay会导致空指针报错

### ISSUE THREAD

**Issue by WentHao** [apache/dubbo-spring-boot-project#528]
java.lang.NullPointerException: null
	at org.apache.dubbo.config.ServiceConfig.export(ServiceConfig.java:335) ~[dubbo-2.7.1.jar:2.7.1]
	at org.apache.dubbo.config.spring.ServiceBean.export(ServiceBean.java:319) ~[dubbo-2.7.1.jar:2.7.1]
	at org.apache.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:113) ~[dubbo-2.7.1.jar:2.7.1]
	at org.apache.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:59) ~[dubbo-2.7.1.jar:2.7.1]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:402) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:359) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:896) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:552) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775) ~[spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) ~[spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) ~[spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:139) [spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
	at org.apache.dubbo.spring.boot.demo.provider.bootstrap.DubboRegistryZooKeeperProviderBootstrap.main(DubboRegistryZooKeeperProviderBootstrap.java:42) [classes/:na]

**Comment by mercyblitz** [comment]
Move to the Dubbo issue in 2.7.4 milestone https://github.com/apache/dubbo/issues/4691
