### ISSUE TITLE
dubbo集成nacos报错

### ISSUE THREAD

**Issue by Skqing** [apache/dubbo-spring-boot-project#551]
```
<!-- Dubbo Nacos registry dependency -->
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>dubbo-registry-nacos</artifactId>
            <version>2.6.6</version>
        </dependency>
        <!-- Alibaba Spring Context extension -->
        <dependency>
            <groupId>com.alibaba.spring</groupId>
            <artifactId>spring-context-support</artifactId>
            <version>1.0.2</version>
        </dependency>
```

```
java.lang.IllegalStateException: Failed to load extension class (interface: interface org.apache.dubbo.registry.RegistryFactory, class line: com.alibaba.dubbo.registry.nacos.NacosRegistryFactory) in jar:file:/E:/repository/com/alibaba/dubbo-registry-nacos/2.6.6/dubbo-registry-nacos-2.6.6.jar!/META-INF/dubbo/com.alibaba.dubbo.registry.RegistryFactory, cause: com/alibaba/dubbo/registry/support/AbstractRegistryFactory
	at org.apache.dubbo.common.extension.ExtensionLoader.loadResource(ExtensionLoader.java:705) ~[dubbo-2.7.1.jar:2.7.1]
	at org.apache.dubbo.common.extension.ExtensionLoader.loadDirectory(ExtensionLoader.java:674) ~[dubbo-2.7.1.jar:2.7.1]
	at org.apache.dubbo.common.extension.ExtensionLoader.loadExtensionClasses(ExtensionLoader.java:635) ~[dubbo-2.7.1.jar:2.7.1]
	at org.apache.dubbo.common.extension.ExtensionLoader.getExtensionClasses(ExtensionLoader.java:619) ~[dubbo-2.7.1.jar:2.7.1]
	at org.apache.dubbo.common.extension.ExtensionLoader.getSupportedExtensions(ExtensionLoader.java:375) ~[dubbo-2.7.1.jar:2.7.1]
	at org.apache.dubbo.common.extension.factory.SpiExtensionFactory.getExtension(SpiExtensionFactory.java:32) ~[dubbo-2.7.1.jar:2.7.1]
	at org.apache.dubbo.common.extension.factory.AdaptiveExtensionFactory.getExtension(AdaptiveExtensionFactory.java:47) ~[dubbo-2.7.1.jar:2.7.1]
	at org.apache.dubbo.common.extension.ExtensionLoader.injectExtension(ExtensionLoader.java:562) ~[dubbo-2.7.1.jar:2.7.1]
	at org.apache.dubbo.common.extension.ExtensionLoader.createExtension(ExtensionLoader.java:531) ~[dubbo-2.7.1.jar:2.7.1]
	at org.apache.dubbo.common.extension.ExtensionLoader.getExtension(ExtensionLoader.java:347) ~[dubbo-2.7.1.jar:2.7.1]
	at org.apache.dubbo.rpc.Protocol$Adaptive.export(Protocol$Adaptive.java) ~[dubbo-2.7.1.jar:2.7.1]
	at org.apache.dubbo.config.ServiceConfig.doExportUrlsFor1Protocol(ServiceConfig.java:559) ~[dubbo-2.7.1.jar:2.7.1]
	at org.apache.dubbo.config.ServiceConfig.doExportUrls(ServiceConfig.java:417) ~[dubbo-2.7.1.jar:2.7.1]
	at org.apache.dubbo.config.ServiceConfig.doExport(ServiceConfig.java:375) ~[dubbo-2.7.1.jar:2.7.1]
	at org.apache.dubbo.config.ServiceConfig.export(ServiceConfig.java:337) ~[dubbo-2.7.1.jar:2.7.1]
	at org.apache.dubbo.config.spring.ServiceBean.export(ServiceBean.java:319) ~[dubbo-2.7.1.jar:2.7.1]
	at org.apache.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:113) ~[dubbo-2.7.1.jar:2.7.1]
	at org.apache.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:59) ~[dubbo-2.7.1.jar:2.7.1]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) [spring-context-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) [spring-context-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) [spring-context-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:402) [spring-context-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:359) [spring-context-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:896) [spring-context-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:163) ~[spring-boot-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:552) [spring-context-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142) ~[spring-boot-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775) ~[spring-boot-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) [spring-boot-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260) [spring-boot-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248) [spring-boot-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at com.hct.example.main.NewDemoMainApplication.main(NewDemoMainApplication.java:25) [classes/:?]
Caused by: java.lang.NoClassDefFoundError: com/alibaba/dubbo/registry/support/AbstractRegistryFactory
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_152]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_152]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_152]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) ~[?:1.8.0_152]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[?:1.8.0_152]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368) ~[?:1.8.0_152]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[?:1.8.0_152]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_152]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361) ~[?:1.8.0_152]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_152]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338) ~[?:1.8.0_152]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_152]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_152]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_152]
	at org.apache.dubbo.common.extension.ExtensionLoader.loadResource(ExtensionLoader.java:702) ~[dubbo-2.7.1.jar:2.7.1]
	... 32 more
Caused by: java.lang.ClassNotFoundException: com.alibaba.dubbo.registry.support.AbstractRegistryFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_152]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_152]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338) ~[?:1.8.0_152]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_152]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_152]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_152]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_152]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) ~[?:1.8.0_152]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[?:1.8.0_152]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368) ~[?:1.8.0_152]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[?:1.8.0_152]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_152]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361) ~[?:1.8.0_152]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_152]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338) ~[?:1.8.0_152]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_152]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_152]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_152]
	at org.apache.dubbo.common.extension.ExtensionLoader.loadResource(ExtensionLoader.java:702) ~[dubbo-2.7.1.jar:2.7.1]
	... 32 more
```

**Comment by mercyblitz** [comment]
Please check your dependencies classpath
