### ISSUE TITLE
引入dubbo-statrer后无法关闭进程，tomcat无法销毁，所有的ApplicationListener全失效

### ISSUE THREAD

**Issue by leduold** [apache/dubbo-spring-boot-project#588]
"container-0" #56 prio=5 os_prio=31 tid=0x00007fcd6facd000 nid=0xa403 waiting on condition [0x0000700003d3b000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
	at java.lang.Thread.sleep(Native Method)
	at org.apache.catalina.core.StandardServer.await(StandardServer.java:408)
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer$1.run(TomcatWebServer.java:181)

**Comment by mercyblitz** [comment]
It's just a thread stack snapshot, does not explain what the problem is.
