### ISSUE TITLE
sample启动报错

### ISSUE THREAD

**Issue by a88066695** [apache/dubbo-spring-boot-project#589]
下载最新例子后，启动auto-configure-samples里的consumer-samples报错，报错信息如下：
Caused by: org.apache.dubbo.rpc.RpcException: Failed to invoke remote method: sayHello, provider: dubbo://127.0.0.1:12345/org.apache.dubbo.spring.boot.demo.consumer.DemoService?application=dubbo-auto-configure-consumer-sample&interface=org.apache.dubbo.spring.boot.demo.consumer.DemoService&lazy=false&pid=18357&qos.enable=false&register.ip=192.168.31.170&remote.application=&revision=1.0.0&side=consumer&sticky=false, cause: org.apache.dubbo.remoting.RemotingException: org.apache.dubbo.remoting.RemotingException: Not found exported service: org.apache.dubbo.spring.boot.demo.consumer.DemoService:12345 in [org.apache.dubbo.spring.boot.demo.consumer.DemoService:1.0.0:12345], may be version or group mismatch , channel: consumer: /192.168.31.170:56296 --> provider: /192.168.31.170:12345, message:RpcInvocation [methodName=sayHello, parameterTypes=[class java.lang.String], arguments=[mercyblitz], attachments={path=org.apache.dubbo.spring.boot.demo.consumer.DemoService, input=266, dubbo=2.0.2, interface=org.apache.dubbo.spring.boot.demo.consumer.DemoService, version=0.0.0}]
org.apache.dubbo.remoting.RemotingException: Not found exported service: org.apache.dubbo.spring.boot.demo.consumer.DemoService:12345 in [org.apache.dubbo.spring.boot.demo.consumer.DemoService:1.0.0:12345], may be version or group mismatch , channel: consumer: /192.168.31.170:56296 --> provider: /192.168.31.170:12345, message:RpcInvocation [methodName=sayHello, parameterTypes=[class java.lang.String], arguments=[mercyblitz], attachments={path=org.apache.dubbo.spring.boot.demo.consumer.DemoService, input=266, dubbo=2.0.2, interface=org.apache.dubbo.spring.boot.demo.consumer.DemoService, version=0.0.0}]
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol.getInvoker(DubboProtocol.java:266)
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:127)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:102)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:193)
	at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:51)
	at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:57)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

	at org.apache.dubbo.rpc.protocol.AsyncToSyncInvoker.invoke(AsyncToSyncInvoker.java:65) ~[dubbo-2.7.3.jar:2.7.3]
	at org.apache.dubbo.rpc.listener.ListenerInvokerWrapper.invoke(ListenerInvokerWrapper.java:78) ~[dubbo-2.7.3.jar:2.7.3]
	at org.apache.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:92) ~[dubbo-2.7.3.jar:2.7.3]
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:82) ~[dubbo-2.7.3.jar:2.7.3]
	at org.apache.dubbo.rpc.protocol.dubbo.filter.FutureFilter.invoke(FutureFilter.java:54) ~[dubbo-2.7.3.jar:2.7.3]
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:82) ~[dubbo-2.7.3.jar:2.7.3]
	at org.apache.dubbo.rpc.filter.ConsumerContextFilter.invoke(ConsumerContextFilter.java:58) ~[dubbo-2.7.3.jar:2.7.3]
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:82) ~[dubbo-2.7.3.jar:2.7.3]
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$CallbackRegistrationInvoker.invoke(ProtocolFilterWrapper.java:157) ~[dubbo-2.7.3.jar:2.7.3]
	at org.apache.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:55) ~[dubbo-2.7.3.jar:2.7.3]
	at org.apache.dubbo.common.bytecode.proxy0.sayHello(proxy0.java) ~[dubbo-2.7.3.jar:2.7.3]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_162]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_162]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_162]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_162]
	at org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor$ReferenceBeanInvocationHandler.invoke(ReferenceAnnotationBeanPostProcessor.java:260) ~[dubbo-2.7.3.jar:2.7.3]
	at com.sun.proxy.$Proxy37.sayHello(Unknown Source) ~[na:na]
	at org.apache.dubbo.spring.boot.demo.consumer.bootstrap.DubboAutoConfigurationConsumerBootstrap.lambda$runner$0(DubboAutoConfigurationConsumerBootstrap.java:47) [classes/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:770) [spring-boot-2.1.6.RELEASE.jar:2.1.6.RELEASE]
	... 5 common frames omitted

**Comment by a88066695** [comment]
好像是@Reference的配置项version没有起作用
<img width="507" alt="屏幕快照 2019-08-25 下午12 43 24" src="https://user-images.githubusercontent.com/13597174/63645668-12423100-c736-11e9-92ca-01ed1c346198.png">

**Comment by ayufish** [comment]
我也出现了同样的问

> 好像是@reference的配置项version没有起作用
> <img alt="屏幕快照 2019-08-25 下午12 43 24" width="507" src="https://user-images.githubusercontent.com/13597174/63645668-12423100-c736-11e9-92ca-01ed1c346198.png">

我也出现了同样的问题，似乎version一直是默认的0.0.0

**Comment by 6westboy9** [comment]
是的，我也是，求解呀

**Comment by 6westboy9** [comment]
参见：https://github.com/apache/dubbo/issues/4734

**Comment by xiaofanTo** [comment]
在你Reference注解上的url后加上版本号，例如 **    @Reference(version = "1.0.0", url = "dubbo://127.0.0.1:12345?version=1.0.0")**

**Comment by mercyblitz** [comment]
This issue had been fixed
