### ISSUE TITLE
刚开始跑第一个Demo报java.lang.IllegalStateException: Failed to execute ApplicationRunner

### ISSUE THREAD

**Issue by 6westboy9** [apache/dubbo-spring-boot-project#601]
自己clone项目之后，在本地跑第一个项目：dubbo-spring-boot-samples时，provider启动成功，但是consumer启动时就抛出如下错误：

**provider端部分启动日志：**

```
2019-09-06 11:11:39.156  INFO 14144 --- [           main] org.apache.dubbo.config.AbstractConfig   :  [DUBBO] The service ready on spring started. service: org.apache.dubbo.spring.boot.demo.consumer.DemoService, dubbo version: 2.7.3, current host: 169.254.152.173
2019-09-06 11:11:39.225  WARN 14144 --- [           main] org.apache.dubbo.config.AbstractConfig   :  [DUBBO] There's no valid metadata config found, if you are using the simplified mode of registry url, please make sure you have a metadata address configured properly., dubbo version: 2.7.3, current host: 169.254.152.173
2019-09-06 11:11:39.310  INFO 14144 --- [           main] org.apache.dubbo.config.AbstractConfig   :  [DUBBO] Export dubbo service org.apache.dubbo.spring.boot.demo.consumer.DemoService to local registry url : injvm://127.0.0.1/org.apache.dubbo.spring.boot.demo.consumer.DemoService?anyhost=true&application=dubbo-auto-configuration-provider-demo&bean.name=ServiceBean:org.apache.dubbo.spring.boot.demo.consumer.DemoService:1.0.0&bind.ip=169.254.152.173&bind.port=12345&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&interface=org.apache.dubbo.spring.boot.demo.consumer.DemoService&methods=sayHello&pid=14144&qos.enable=false&register=true&release=2.7.3&revision=1.0.0&side=provider&timestamp=1567739499227&version=1.0.0, dubbo version: 2.7.3, current host: 169.254.152.173
2019-09-06 11:11:39.310  INFO 14144 --- [           main] org.apache.dubbo.config.AbstractConfig   :  [DUBBO] Export dubbo service org.apache.dubbo.spring.boot.demo.consumer.DemoService to url dubbo://169.254.152.173:12345/org.apache.dubbo.spring.boot.demo.consumer.DemoService?anyhost=true&application=dubbo-auto-configuration-provider-demo&bean.name=ServiceBean:org.apache.dubbo.spring.boot.demo.consumer.DemoService:1.0.0&bind.ip=169.254.152.173&bind.port=12345&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&interface=org.apache.dubbo.spring.boot.demo.consumer.DemoService&methods=sayHello&pid=14144&qos.enable=false&register=true&release=2.7.3&revision=1.0.0&side=provider&timestamp=1567739499227&version=1.0.0, dubbo version: 2.7.3, current host: 169.254.152.173
2019-09-06 11:11:39.808  INFO 14144 --- [           main] o.a.d.remoting.transport.AbstractServer  :  [DUBBO] Start NettyServer bind /0.0.0.0:12345, export /169.254.152.173:12345, dubbo version: 2.7.3, current host: 169.254.152.173
2019-09-06 11:11:39.812  INFO 14144 --- [           main] .DubboAutoConfigurationProviderBootstrap : Started DubboAutoConfigurationProviderBootstrap in 2.256 seconds (JVM running for 2.917)
2019-09-06 11:11:39.815  INFO 14144 --- [pool-1-thread-1] .b.c.e.AwaitingNonWebApplicationListener :  [Dubbo] Current Spring Boot Application is await...
2019-09-06 11:13:35.515  INFO 14144 --- [erverWorker-3-1] o.a.d.r.p.dubbo.CallbackServiceCodec     :  [DUBBO] Not found exported service: org.apache.dubbo.spring.boot.demo.consumer.DemoService:12345 in [org.apache.dubbo.spring.boot.demo.consumer.DemoService:1.0.0:12345], may be version or group mismatch , channel: consumer: /169.254.152.173:54254 --> provider: /169.254.152.173:12345, message:RpcInvocation [methodName=sayHello, parameterTypes=[class java.lang.String], arguments=null, attachments={path=org.apache.dubbo.spring.boot.demo.consumer.DemoService, dubbo=2.0.2, interface=org.apache.dubbo.spring.boot.demo.consumer.DemoService, version=0.0.0}], dubbo version: 2.7.3, current host: 169.254.152.173
```

**consumer端的错误日志：**

```
2019-09-06 11:13:35.540 ERROR 9472 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Failed to execute ApplicationRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:773) [spring-boot-2.1.6.RELEASE.jar:2.1.6.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:760) [spring-boot-2.1.6.RELEASE.jar:2.1.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:318) [spring-boot-2.1.6.RELEASE.jar:2.1.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1213) [spring-boot-2.1.6.RELEASE.jar:2.1.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1202) [spring-boot-2.1.6.RELEASE.jar:2.1.6.RELEASE]
	at org.apache.dubbo.spring.boot.demo.consumer.bootstrap.DubboAutoConfigurationConsumerBootstrap.main(DubboAutoConfigurationConsumerBootstrap.java:42) [classes/:na]
Caused by: org.apache.dubbo.rpc.RpcException: Failed to invoke remote method: sayHello, provider: dubbo://127.0.0.1:12345/org.apache.dubbo.spring.boot.demo.consumer.DemoService?application=dubbo-auto-configure-consumer-sample&interface=org.apache.dubbo.spring.boot.demo.consumer.DemoService&lazy=false&pid=9472&qos.enable=false&register.ip=169.254.152.173&remote.application=&revision=1.0.0&side=consumer&sticky=false, cause: org.apache.dubbo.remoting.RemotingException: org.apache.dubbo.remoting.RemotingException: Not found exported service: org.apache.dubbo.spring.boot.demo.consumer.DemoService:12345 in [org.apache.dubbo.spring.boot.demo.consumer.DemoService:1.0.0:12345], may be version or group mismatch , channel: consumer: /169.254.152.173:54254 --> provider: /169.254.152.173:12345, message:RpcInvocation [methodName=sayHello, parameterTypes=[class java.lang.String], arguments=[mercyblitz], attachments={path=org.apache.dubbo.spring.boot.demo.consumer.DemoService, input=266, dubbo=2.0.2, interface=org.apache.dubbo.spring.boot.demo.consumer.DemoService, version=0.0.0}]
org.apache.dubbo.remoting.RemotingException: Not found exported service: org.apache.dubbo.spring.boot.demo.consumer.DemoService:12345 in [org.apache.dubbo.spring.boot.demo.consumer.DemoService:1.0.0:12345], may be version or group mismatch , channel: consumer: /169.254.152.173:54254 --> provider: /169.254.152.173:12345, message:RpcInvocation [methodName=sayHello, parameterTypes=[class java.lang.String], arguments=[mercyblitz], attachments={path=org.apache.dubbo.spring.boot.demo.consumer.DemoService, input=266, dubbo=2.0.2, interface=org.apache.dubbo.spring.boot.demo.consumer.DemoService, version=0.0.0}]
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol.getInvoker(DubboProtocol.java:266)
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:127)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:102)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:193)
	at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:51)
	at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:57)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

	at org.apache.dubbo.rpc.protocol.AsyncToSyncInvoker.invoke(AsyncToSyncInvoker.java:65) ~[dubbo-2.7.3.jar:2.7.3]
	at org.apache.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:92) ~[dubbo-2.7.3.jar:2.7.3]
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:82) ~[dubbo-2.7.3.jar:2.7.3]
	at org.apache.dubbo.rpc.protocol.dubbo.filter.FutureFilter.invoke(FutureFilter.java:54) ~[dubbo-2.7.3.jar:2.7.3]
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:82) ~[dubbo-2.7.3.jar:2.7.3]
	at org.apache.dubbo.rpc.filter.ConsumerContextFilter.invoke(ConsumerContextFilter.java:58) ~[dubbo-2.7.3.jar:2.7.3]
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:82) ~[dubbo-2.7.3.jar:2.7.3]
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$CallbackRegistrationInvoker.invoke(ProtocolFilterWrapper.java:157) ~[dubbo-2.7.3.jar:2.7.3]
	at org.apache.dubbo.rpc.listener.ListenerInvokerWrapper.invoke(ListenerInvokerWrapper.java:78) ~[dubbo-2.7.3.jar:2.7.3]
	at org.apache.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:55) ~[dubbo-2.7.3.jar:2.7.3]
	at org.apache.dubbo.common.bytecode.proxy0.sayHello(proxy0.java) ~[dubbo-2.7.3.jar:2.7.3]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_202]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_202]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_202]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_202]
	at org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor$ReferenceBeanInvocationHandler.invoke(ReferenceAnnotationBeanPostProcessor.java:260) ~[dubbo-2.7.3.jar:2.7.3]
	at com.sun.proxy.$Proxy38.sayHello(Unknown Source) ~[na:na]
	at org.apache.dubbo.spring.boot.demo.consumer.bootstrap.DubboAutoConfigurationConsumerBootstrap.lambda$runner$0(DubboAutoConfigurationConsumerBootstrap.java:47) [classes/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:770) [spring-boot-2.1.6.RELEASE.jar:2.1.6.RELEASE]
	... 5 common frames omitted
Caused by: java.util.concurrent.ExecutionException: org.apache.dubbo.remoting.RemotingException: org.apache.dubbo.remoting.RemotingException: Not found exported service: org.apache.dubbo.spring.boot.demo.consumer.DemoService:12345 in [org.apache.dubbo.spring.boot.demo.consumer.DemoService:1.0.0:12345], may be version or group mismatch , channel: consumer: /169.254.152.173:54254 --> provider: /169.254.152.173:12345, message:RpcInvocation [methodName=sayHello, parameterTypes=[class java.lang.String], arguments=[mercyblitz], attachments={path=org.apache.dubbo.spring.boot.demo.consumer.DemoService, input=266, dubbo=2.0.2, interface=org.apache.dubbo.spring.boot.demo.consumer.DemoService, version=0.0.0}]
org.apache.dubbo.remoting.RemotingException: Not found exported service: org.apache.dubbo.spring.boot.demo.consumer.DemoService:12345 in [org.apache.dubbo.spring.boot.demo.consumer.DemoService:1.0.0:12345], may be version or group mismatch , channel: consumer: /169.254.152.173:54254 --> provider: /169.254.152.173:12345, message:RpcInvocation [methodName=sayHello, parameterTypes=[class java.lang.String], arguments=[mercyblitz], attachments={path=org.apache.dubbo.spring.boot.demo.consumer.DemoService, input=266, dubbo=2.0.2, interface=org.apache.dubbo.spring.boot.demo.consumer.DemoService, version=0.0.0}]
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol.getInvoker(DubboProtocol.java:266)
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:127)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:102)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:193)
	at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:51)
	at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:57)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357) ~[na:1.8.0_202]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915) ~[na:1.8.0_202]
	at org.apache.dubbo.rpc.protocol.AsyncToSyncInvoker.invoke(AsyncToSyncInvoker.java:56) ~[dubbo-2.7.3.jar:2.7.3]
	... 23 common frames omitted
Caused by: org.apache.dubbo.remoting.RemotingException: org.apache.dubbo.remoting.RemotingException: Not found exported service: org.apache.dubbo.spring.boot.demo.consumer.DemoService:12345 in [org.apache.dubbo.spring.boot.demo.consumer.DemoService:1.0.0:12345], may be version or group mismatch , channel: consumer: /169.254.152.173:54254 --> provider: /169.254.152.173:12345, message:RpcInvocation [methodName=sayHello, parameterTypes=[class java.lang.String], arguments=[mercyblitz], attachments={path=org.apache.dubbo.spring.boot.demo.consumer.DemoService, input=266, dubbo=2.0.2, interface=org.apache.dubbo.spring.boot.demo.consumer.DemoService, version=0.0.0}]
org.apache.dubbo.remoting.RemotingException: Not found exported service: org.apache.dubbo.spring.boot.demo.consumer.DemoService:12345 in [org.apache.dubbo.spring.boot.demo.consumer.DemoService:1.0.0:12345], may be version or group mismatch , channel: consumer: /169.254.152.173:54254 --> provider: /169.254.152.173:12345, message:RpcInvocation [methodName=sayHello, parameterTypes=[class java.lang.String], arguments=[mercyblitz], attachments={path=org.apache.dubbo.spring.boot.demo.consumer.DemoService, input=266, dubbo=2.0.2, interface=org.apache.dubbo.spring.boot.demo.consumer.DemoService, version=0.0.0}]
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol.getInvoker(DubboProtocol.java:266)
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:127)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:102)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:193)
	at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:51)
	at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:57)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

	at org.apache.dubbo.remoting.exchange.support.DefaultFuture.doReceived(DefaultFuture.java:191) ~[dubbo-2.7.3.jar:2.7.3]
	at org.apache.dubbo.remoting.exchange.support.DefaultFuture.received(DefaultFuture.java:153) ~[dubbo-2.7.3.jar:2.7.3]
	at org.apache.dubbo.remoting.exchange.support.DefaultFuture.received(DefaultFuture.java:141) ~[dubbo-2.7.3.jar:2.7.3]
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleResponse(HeaderExchangeHandler.java:62) ~[dubbo-2.7.3.jar:2.7.3]
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:199) ~[dubbo-2.7.3.jar:2.7.3]
	at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:51) ~[dubbo-2.7.3.jar:2.7.3]
	at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:57) ~[dubbo-2.7.3.jar:2.7.3]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_202]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_202]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_202]
```

**Comment by 6westboy9** [comment]
已经解决了，参考：https://github.com/apache/dubbo/issues/4734
