### ISSUE TITLE
dubbo同一个服务启动两个，service的group和version不同，消费者Reference指定一个group，version，启动报错

### ISSUE THREAD

**Issue by khiker007** [apache/dubbo-spring-boot-project#631]
同一个dubbo服务，有两个版本，在service注解中使用不同的group和version，但是在消费端使用Reference注解，指定引用其中一个group和version启动报错，把不引用的再nacos中下线，则可以正常启动

two dubbo provider,same project name,but have diff provider group and version,consumer Reference one of the group and version,Not found exported service

希望同一服务的service可以支持不同版本同时在线，调用端根据service的group和version调用不同的服务
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'initKlineCache' defined in file [E:\IdeaWorkspace\fshares\fshares-exchange\web\websocket-market\out\production\classes\com\fshares\chain\market\config\InitKlineCache.class]: Invocation of init method failed; nested exception is org.apache.dubbo.rpc.RpcException: Failed to invoke the method getLasted in the service com.fshares.chain.service.market.IKlineService. Tried 1 times of the providers [172.16.17.227:28088] (1/2) from the registry localhost:9090 on the consumer 10.0.75.1 using the dubbo version 2.7.3. Last error is: Failed to invoke remote method: getLasted, provider: dubbo://172.16.17.227:28088/com.fshares.chain.service.market.IKlineService?accepts=1000&anyhost=true&application=websocket-market&bean.name=ServiceBean:com.fshares.chain.service.market.IKlineService:1.0.2:fsdex-1&buffer=8192&check=false&delay=-1&deprecated=false&dispatcher=message&dubbo=2.0.2&dynamic=true&generic=false&group=fsdex-1&heartbeat=5000&interface=com.fshares.chain.service.market.IKlineService&keep.alive=true&lazy=false&methods=getLasted,getById,getList,updateOne,getPrev&payload=16777216&pid=11092&qos.enable=false&register=true&register.ip=10.0.75.1&release=2.7.3&remote.application=service-market&retries=0&revision=1.0.2&serialization=kryo&side=consumer&status=server&sticky=false&timeout=5000&timestamp=1575283940635&version=1.0.2, cause: org.apache.dubbo.remoting.RemotingException: org.apache.dubbo.remoting.RemotingException: Not found exported service: fsdex-1/com.fshares.chain.service.market.IKlineService:1.0.2:28088 in [service-market/com.alibaba.cloud.dubbo.service.DubboMetadataService:1.0.0:28088, fsdex/com.fshares.chain.service.market.IExchangeRateService:1.0.1:28088, fsdex/com.fshares.chain.service.market.ICurrencyPairTrendService:1.0.1:28088, fsdex/com.fshares.chain.service.market.IKlineService:1.0.1:28088], may be version or group mismatch , channel: consumer: /172.16.17.5:62920 --> provider: /172.16.17.227:28088, message:RpcInvocation [methodName=getLasted, parameterTypes=[class java.lang.String, class java.lang.String], arguments=[FEOS_FBTC, 1m], attachments={path=com.fshares.chain.service.market.IKlineService, input=249, dubbo=2.0.2, interface=com.fshares.chain.service.market.IKlineService, version=1.0.2, timeout=5000, group=fsdex-1}]
org.apache.dubbo.remoting.RemotingException: Not found exported service: fsdex-1/com.fshares.chain.service.market.IKlineService:1.0.2:28088 in [service-market/com.alibaba.cloud.dubbo.service.DubboMetadataService:1.0.0:28088, fsdex/com.fshares.chain.service.market.IExchangeRateService:1.0.1:28088, fsdex/com.fshares.chain.service.market.ICurrencyPairTrendService:1.0.1:28088, fsdex/com.fshares.chain.service.market.IKlineService:1.0.1:28088], may be version or group mismatch , channel: consumer: /172.16.17.5:62920 --> provider: /172.16.17.227:28088, message:RpcInvocation [methodName=getLasted, parameterTypes=[class java.lang.String, class java.lang.String], arguments=[FEOS_FBTC, 1m], attachments={path=com.fshares.chain.service.market.IKlineService, input=249, dubbo=2.0.2, interface=com.fshares.chain.service.market.IKlineService, version=1.0.2, timeout=5000, group=fsdex-1}]
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol.getInvoker(DubboProtocol.java:266)
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:127)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:102)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:193)
	at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:51)
	at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:57)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1778)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:847)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:744)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:391)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:140)
	at com.fshares.chain.WebsocketApplication.main(WebsocketApplication.java:13)
Caused by: org.apache.dubbo.rpc.RpcException: Failed to invoke the method getLasted in the service com.fshares.chain.service.market.IKlineService. Tried 1 times of the providers [172.16.17.227:28088] (1/2) from the registry localhost:9090 on the consumer 10.0.75.1 using the dubbo version 2.7.3. Last error is: Failed to invoke remote method: getLasted, provider: dubbo://172.16.17.227:28088/com.fshares.chain.service.market.IKlineService?accepts=1000&anyhost=true&application=websocket-market&bean.name=ServiceBean:com.fshares.chain.service.market.IKlineService:1.0.2:fsdex-1&buffer=8192&check=false&delay=-1&deprecated=false&dispatcher=message&dubbo=2.0.2&dynamic=true&generic=false&group=fsdex-1&heartbeat=5000&interface=com.fshares.chain.service.market.IKlineService&keep.alive=true&lazy=false&methods=getLasted,getById,getList,updateOne,getPrev&payload=16777216&pid=11092&qos.enable=false&register=true&register.ip=10.0.75.1&release=2.7.3&remote.application=service-market&retries=0&revision=1.0.2&serialization=kryo&side=consumer&status=server&sticky=false&timeout=5000&timestamp=1575283940635&version=1.0.2, cause: org.apache.dubbo.remoting.RemotingException: org.apache.dubbo.remoting.RemotingException: Not found exported service: fsdex-1/com.fshares.chain.service.market.IKlineService:1.0.2:28088 in [service-market/com.alibaba.cloud.dubbo.service.DubboMetadataService:1.0.0:28088, fsdex/com.fshares.chain.service.market.IExchangeRateService:1.0.1:28088, fsdex/com.fshares.chain.service.market.ICurrencyPairTrendService:1.0.1:28088, fsdex/com.fshares.chain.service.market.IKlineService:1.0.1:28088], may be version or group mismatch , channel: consumer: /172.16.17.5:62920 --> provider: /172.16.17.227:28088, message:RpcInvocation [methodName=getLasted, parameterTypes=[class java.lang.String, class java.lang.String], arguments=[FEOS_FBTC, 1m], attachments={path=com.fshares.chain.service.market.IKlineService, input=249, dubbo=2.0.2, interface=com.fshares.chain.service.market.IKlineService, version=1.0.2, timeout=5000, group=fsdex-1}]
org.apache.dubbo.remoting.RemotingException: Not found exported service: fsdex-1/com.fshares.chain.service.market.IKlineService:1.0.2:28088 in [service-market/com.alibaba.cloud.dubbo.service.DubboMetadataService:1.0.0:28088, fsdex/com.fshares.chain.service.market.IExchangeRateService:1.0.1:28088, fsdex/com.fshares.chain.service.market.ICurrencyPairTrendService:1.0.1:28088, fsdex/com.fshares.chain.service.market.IKlineService:1.0.1:28088], may be version or group mismatch , channel: consumer: /172.16.17.5:62920 --> provider: /172.16.17.227:28088, message:RpcInvocation [methodName=getLasted, parameterTypes=[class java.lang.String, class java.lang.String], arguments=[FEOS_FBTC, 1m], attachments={path=com.fshares.chain.service.market.IKlineService, input=249, dubbo=2.0.2, interface=com.fshares.chain.service.market.IKlineService, version=1.0.2, timeout=5000, group=fsdex-1}]
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol.getInvoker(DubboProtocol.java:266)
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:127)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:102)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:193)
	at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:51)
	at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:57)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at org.apache.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:113)
	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:248)
	at org.apache.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:78)
	at org.apache.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:55)
	at org.apache.dubbo.common.bytecode.proxy1.getLasted(proxy1.java)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor$ReferenceBeanInvocationHandler.invoke(ReferenceAnnotationBeanPostProcessor.java:260)
	at com.sun.proxy.$Proxy157.getLasted(Unknown Source)
	at com.fshares.chain.market.config.InitKlineCache.lambda$null$0(InitKlineCache.java:39)
	at java.util.Arrays$ArrayList.forEach(Arrays.java:3880)
	at com.fshares.chain.market.config.InitKlineCache.lambda$afterPropertiesSet$1(InitKlineCache.java:31)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.fshares.chain.market.config.InitKlineCache.afterPropertiesSet(InitKlineCache.java:31)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1837)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1774)
	... 15 common frames omitted
Caused by: java.util.concurrent.ExecutionException: org.apache.dubbo.remoting.RemotingException: org.apache.dubbo.remoting.RemotingException: Not found exported service: fsdex-1/com.fshares.chain.service.market.IKlineService:1.0.2:28088 in [service-market/com.alibaba.cloud.dubbo.service.DubboMetadataService:1.0.0:28088, fsdex/com.fshares.chain.service.market.IExchangeRateService:1.0.1:28088, fsdex/com.fshares.chain.service.market.ICurrencyPairTrendService:1.0.1:28088, fsdex/com.fshares.chain.service.market.IKlineService:1.0.1:28088], may be version or group mismatch , channel: consumer: /172.16.17.5:62920 --> provider: /172.16.17.227:28088, message:RpcInvocation [methodName=getLasted, parameterTypes=[class java.lang.String, class java.lang.String], arguments=[FEOS_FBTC, 1m], attachments={path=com.fshares.chain.service.market.IKlineService, input=249, dubbo=2.0.2, interface=com.fshares.chain.service.market.IKlineService, version=1.0.2, timeout=5000, group=fsdex-1}]
org.apache.dubbo.remoting.RemotingException: Not found exported service: fsdex-1/com.fshares.chain.service.market.IKlineService:1.0.2:28088 in [service-market/com.alibaba.cloud.dubbo.service.DubboMetadataService:1.0.0:28088, fsdex/com.fshares.chain.service.market.IExchangeRateService:1.0.1:28088, fsdex/com.fshares.chain.service.market.ICurrencyPairTrendService:1.0.1:28088, fsdex/com.fshares.chain.service.market.IKlineService:1.0.1:28088], may be version or group mismatch , channel: consumer: /172.16.17.5:62920 --> provider: /172.16.17.227:28088, message:RpcInvocation [methodName=getLasted, parameterTypes=[class java.lang.String, class java.lang.String], arguments=[FEOS_FBTC, 1m], attachments={path=com.fshares.chain.service.market.IKlineService, input=249, dubbo=2.0.2, interface=com.fshares.chain.service.market.IKlineService, version=1.0.2, timeout=5000, group=fsdex-1}]
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol.getInvoker(DubboProtocol.java:266)
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:127)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:102)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:193)
	at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:51)
	at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:57)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
	at org.apache.dubbo.rpc.protocol.AsyncToSyncInvoker.invoke(AsyncToSyncInvoker.java:56)
	at org.apache.dubbo.rpc.listener.ListenerInvokerWrapper.invoke(ListenerInvokerWrapper.java:78)
	at org.apache.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:92)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:82)
	at org.apache.dubbo.rpc.protocol.dubbo.filter.FutureFilter.invoke(FutureFilter.java:54)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:82)
	at org.apache.dubbo.rpc.filter.ConsumerContextFilter.invoke(ConsumerContextFilter.java:58)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:82)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$CallbackRegistrationInvoker.invoke(ProtocolFilterWrapper.java:157)
	at org.apache.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:56)
	at org.apache.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:82)
	... 32 common frames omitted
Caused by: org.apache.dubbo.remoting.RemotingException: org.apache.dubbo.remoting.RemotingException: Not found exported service: fsdex-1/com.fshares.chain.service.market.IKlineService:1.0.2:28088 in [service-market/com.alibaba.cloud.dubbo.service.DubboMetadataService:1.0.0:28088, fsdex/com.fshares.chain.service.market.IExchangeRateService:1.0.1:28088, fsdex/com.fshares.chain.service.market.ICurrencyPairTrendService:1.0.1:28088, fsdex/com.fshares.chain.service.market.IKlineService:1.0.1:28088], may be version or group mismatch , channel: consumer: /172.16.17.5:62920 --> provider: /172.16.17.227:28088, message:RpcInvocation [methodName=getLasted, parameterTypes=[class java.lang.String, class java.lang.String], arguments=[FEOS_FBTC, 1m], attachments={path=com.fshares.chain.service.market.IKlineService, input=249, dubbo=2.0.2, interface=com.fshares.chain.service.market.IKlineService, version=1.0.2, timeout=5000, group=fsdex-1}]
org.apache.dubbo.remoting.RemotingException: Not found exported service: fsdex-1/com.fshares.chain.service.market.IKlineService:1.0.2:28088 in [service-market/com.alibaba.cloud.dubbo.service.DubboMetadataService:1.0.0:28088, fsdex/com.fshares.chain.service.market.IExchangeRateService:1.0.1:28088, fsdex/com.fshares.chain.service.market.ICurrencyPairTrendService:1.0.1:28088, fsdex/com.fshares.chain.service.market.IKlineService:1.0.1:28088], may be version or group mismatch , channel: consumer: /172.16.17.5:62920 --> provider: /172.16.17.227:28088, message:RpcInvocation [methodName=getLasted, parameterTypes=[class java.lang.String, class java.lang.String], arguments=[FEOS_FBTC, 1m], attachments={path=com.fshares.chain.service.market.IKlineService, input=249, dubbo=2.0.2, interface=com.fshares.chain.service.market.IKlineService, version=1.0.2, timeout=5000, group=fsdex-1}]
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol.getInvoker(DubboProtocol.java:266)
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:127)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:102)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:193)
	at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:51)
	at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:57)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at org.apache.dubbo.remoting.exchange.support.DefaultFuture.doReceived(DefaultFuture.java:191)
	at org.apache.dubbo.remoting.exchange.support.DefaultFuture.received(DefaultFuture.java:153)
	at org.apache.dubbo.remoting.exchange.support.DefaultFuture.received(DefaultFuture.java:141)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleResponse(HeaderExchangeHandler.java:62)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:199)
	at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:51)
	at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:57)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by mercyblitz** [comment]
Which version of dubbo did you use?

**Comment by khiker007** [comment]
> Which version of dubbo did you use?

2.7.3

**Comment by mercyblitz** [comment]
Did you try yo Dubbo 2.7.4?

**Comment by khiker007** [comment]
> Did you try Dubbo 2.7.4?

I dont try 2.7.4
I used spring-cloud-alibaba2.1.1,but this version dont support 2.7.4,force replace dubbo version will error on start application

**Comment by switchII** [comment]
一样出现，尝试很多次本地调试，升级到2.7.4就不出现

**Comment by khiker007** [comment]
> 本地联调的时候出现这样情况，尝试很多次本地调试，升级到2.7.4就不出现，或者调整回原alibaba版本

是的，现在使用不同group和version就是为了本地联调用，依赖的所有服务都在其他机器，本地调式哪个服务就更换group和version；现在就是用回了dubbo的版本，用了spring cloud alibaba，没有用dubbo-spring-boot，dubbo服务的service直接注册到nacos里是可以的，但是现在的问题是service注册一份，spring cloud alibaba又注册了一份，为了spring boot admin可以使用又需要把service、服务分不同的namespace注册，使用起来很别扭啊

**Comment by khiker007** [comment]
> 本地联调的时候出现这样情况，尝试很多次本地调试，升级到2.7.4就不出现，或者调整回原alibaba版本

2.7.4真的好用么？现在springcloudalibaba还不支持2.7.4，要用2.7.4得自己去修改代码编译包，不是太想花时间去试

**Comment by switchII** [comment]
> > 本地联调的时候出现这样情况，尝试很多次本地调试，升级到2.7.4就不出现，或者调整回原alibaba版本
> 
> 2.7.4真的好用么？现在springcloudalibaba还不支持2.7.4，要用2.7.4得自己去修改代码编译包，不是太想花时间去试

目前，2.7.4版本做的是一些小项目，主要项目还是调整为alibaba版本，考虑稳定为主。

**Comment by mercyblitz** [comment]
This issue has been fixed in Dubbo 2.7.5
