### ISSUE TITLE
start failed when use nacos as registry center and set dubbo.provider.version

### ISSUE THREAD

**Issue by RojerAlone** [apache/dubbo-spring-boot-project#654]
I use dubbo 2.7.5 and dubbo spring boot 2.7.5, but start service failed because NPE.

Like the title, I use nacos as registry center, like: `nacos://127.0.0.1:8848`, and set `dubbo.provider.version=2.0` in the `application.yml` file, when i start my service, I got:

```
java.lang.NullPointerException: null
	at org.apache.dubbo.registry.integration.RegistryProtocol.register(RegistryProtocol.java:178) ~[dubbo-2.7.5.jar:2.7.5]
	at org.apache.dubbo.registry.integration.RegistryProtocol.export(RegistryProtocol.java:209) ~[dubbo-2.7.5.jar:2.7.5]
	at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.export(ProtocolListenerWrapper.java:60) ~[dubbo-2.7.5.jar:2.7.5]
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper.export(ProtocolFilterWrapper.java:143) ~[dubbo-2.7.5.jar:2.7.5]
	at org.apache.dubbo.qos.protocol.QosProtocolWrapper.export(QosProtocolWrapper.java:64) ~[dubbo-2.7.5.jar:2.7.5]
	at org.apache.dubbo.rpc.Protocol$Adaptive.export(Protocol$Adaptive.java) ~[dubbo-2.7.5.jar:2.7.5]
	at org.apache.dubbo.config.ServiceConfig.doExportUrlsFor1Protocol(ServiceConfig.java:470) ~[dubbo-2.7.5.jar:2.7.5]
	at org.apache.dubbo.config.ServiceConfig.doExportUrls(ServiceConfig.java:315) ~[dubbo-2.7.5.jar:2.7.5]
	at org.apache.dubbo.config.ServiceConfig.doExport(ServiceConfig.java:287) ~[dubbo-2.7.5.jar:2.7.5]
	at org.apache.dubbo.config.ServiceConfig.export(ServiceConfig.java:205) ~[dubbo-2.7.5.jar:2.7.5]
```
But if I set version in the `@Service(version="2.0")`, it's ok.
I try it in the `provider-sample` [module](https://github.com/apache/dubbo-spring-boot-project/tree/master/dubbo-spring-boot-samples/auto-configure-samples/provider-sample), just add `dubbo-registry-nacos` dependency and change `application.properties` file.

Yesterday I read the code, it seems that the `version` param in properties file is not  set into `ServiceConfig`, so the [`getUniqueServiceName`](https://github.com/apache/dubbo/blob/dubbo-2.7.5/dubbo-common/src/main/java/org/apache/dubbo/config/ServiceConfigBase.java#L444) return a name without version, the dubbo can't get a [`ProviderModel`](https://github.com/apache/dubbo/blob/dubbo-2.7.5/dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/integration/RegistryProtocol.java#L177) by service key with version, it causes NPE. 

It looks like dubbo spring boot project cause this rather than dubbo, pls check it.

**Comment by RojerAlone** [comment]
@mercyblitz

**Comment by Johnson-Jia** [comment]
@mercyblitz

**Comment by Johnson-Jia** [comment]
@RojerAlone   可以采用如下方式解决版本号问题： 

由原来的：      @Service
修改为如下：  @Service(version = "${dubbo.provider.version}")
