### ISSUE TITLE
dubbo2.7.3升级到2.7.5报IllegalStateException: Invalid name="org.apache.dubbo.config.ProtocolConfig#0" contains illegal character，服务启动失败

### ISSUE THREAD

**Issue by guoguo66** [apache/dubbo-spring-boot-project#683]
下面是我的配置
![image](https://user-images.githubusercontent.com/29192570/76944379-de319600-693b-11ea-9da5-afb8962fe43c.png)
![image](https://user-images.githubusercontent.com/29192570/76944409-ea1d5800-693b-11ea-80ee-3a6f9383ee78.png)
启动报错不支持“#”，问题是我没有配置ProtocolConfig，缺省的，而且没有xml配置reference，都是注解注入
请问怎么解决这个问题呢

**Comment by cat160** [comment]
我也遇到这个问题，看代码是这里正则判断有问题
![image](https://user-images.githubusercontent.com/29987847/77225911-c0b83280-6bae-11ea-9497-4fdff1105538.png)

**Comment by cat160** [comment]
开了代码，读取配置的时候这个正则这里过不去
![image](https://user-images.githubusercontent.com/29987847/77225933-e7766900-6bae-11ea-8fcb-aa59a5302eba.png)
java.lang.IllegalStateException: Invalid name="org.apache.dubbo.config.ApplicationConfig#0" contains illegal character, only digit, letter, '-', '_' or '.' is legal.
	at org.apache.dubbo.config.utils.ConfigValidationUtils.checkProperty(ConfigValidationUtils.java:593) ~[dubbo-2.7.5.jar:2.7.5]
	at org.apache.dubbo.config.utils.ConfigValidationUtils.checkName(ConfigValidationUtils.java:551) ~[dubbo-2.7.5.jar:2.7.5]
	at org.apache.dubbo.config.utils.ConfigValidationUtils.validateApplicationConfig(ConfigValidationUtils.java:386) ~[dubbo-2.7.5.jar:2.7.5]
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.checkGlobalConfigs(DubboBootstrap.java:529) ~[dubbo-2.7.5.jar:2.7.5]
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.initialize(DubboBootstrap.java:514) ~[dubbo-2.7.5.jar:2.7.5]
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.start(DubboBootstrap.java:698) ~[dubbo-2.7.5.jar:2.7.5]

**Comment by cat160** [comment]
我也遇到这个问题，看了代码，是这个正则过不去
![image](https://user-images.githubusercontent.com/29987847/77225968-2efcf500-6baf-11ea-8bc1-238cddb2a8d0.png)

**Comment by huadong** [comment]
碰到同样问题，貌似项目没人管了。

**Comment by mercyblitz** [comment]
It's an issue of Dubbo, please trace https://github.com/apache/dubbo/issues/5945
