### ISSUE TITLE
a app is both provider and consumer,but throw exception when start up

### ISSUE THREAD

**Issue by StevenKin** [apache/dubbo-spring-boot-project#719]
```
@Service
public class TestServiceImp implements TestService {
    @Reference
    private EchoService echoService;

    public String hello() {
        System.out.println("testService " + RpcContext.getContext().getAttachments());
        return echoService.echo();
    }

}
```
```
@Configuration
@EnableDubbo(scanBasePackages = "me.stevenkin.dubbo.test.provider")
public class ProviderConfiguation {
    @Bean
    public ApplicationConfig applicationConfig() {
        ApplicationConfig applicationConfig = new ApplicationConfig();
        return applicationConfig;
    }

    @Bean
    public com.alibaba.dubbo.config.ProviderConfig providerConfig() {
        return new com.alibaba.dubbo.config.ProviderConfig();
    }

    @Bean
    public RegistryConfig registryConfig() {
        return new RegistryConfig("zookeeper://127.0.0.1:2181");
    }

    @Bean
    public ProtocolConfig protocolConfig() {
        ProtocolConfig protocolConfig = new ProtocolConfig();
        protocolConfig.setName("dubbo");
        protocolConfig.setPort(-1);
        return protocolConfig;
    }
}
```
exception stack
```
Caused by: java.lang.IllegalStateException: Duplicate application configs: <dubbo:application logger="slf4j" /> and <dubbo:application />
	at com.alibaba.dubbo.config.spring.ReferenceBean.afterPropertiesSet(ReferenceBean.java:98)
	at com.alibaba.dubbo.config.spring.beans.factory.annotation.ReferenceBeanBuilder.postConfigureBean(ReferenceBeanBuilder.java:120)
	at com.alibaba.dubbo.config.spring.beans.factory.annotation.ReferenceBeanBuilder.postConfigureBean(ReferenceBeanBuilder.java:34)
	at com.alibaba.dubbo.config.spring.beans.factory.annotation.AbstractAnnotationConfigBeanBuilder.configureBean(AbstractAnnotationConfigBeanBuilder.java:106)
	at com.alibaba.dubbo.config.spring.beans.factory.annotation.AbstractAnnotationConfigBeanBuilder.build(AbstractAnnotationConfigBeanBuilder.java:72)
	at com.alibaba.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor.buildReferenceBean(ReferenceAnnotationBeanPostProcessor.java:333)
	at com.alibaba.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor.access$100(ReferenceAnnotationBeanPostProcessor.java:60)
	at com.alibaba.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor$ReferenceFieldElement.inject(ReferenceAnnotationBeanPostProcessor.java:311)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	at com.alibaba.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor.postProcessPropertyValues(ReferenceAnnotationBeanPostProcessor.java:87)
	... 12 more
```

**Comment by mercyblitz** [comment]
Please use the Dubbo 2.7.x
