### ISSUE TITLE
在openjdk15  apache-zookeeper-3.6.2-bin下，dubbo-spring-boot-project/dubbo-spring-boot-samples/registry-samples/zookeeper-samples项目报错

### ISSUE THREAD

**Issue by felixyin** [apache/dubbo-spring-boot-project#767]
➜  dubbo  /usr/lib/jvm/java-1.15.0-openjdk-amd64/bin/java -XX:+ShowCodeDetailsInExceptionMessages -Dfile.encoding=UTF-8 @/tmp/cp_1j6f4rp1yun3giog2xjte3k9u.argfile org.apache.dubbo.spring.boot.sample.provider.bootstrap.DubboRegistryZooKeeperProviderBootstrap 
log4j:WARN No appenders could be found for logger (org.apache.dubbo.common.logger.LoggerFactory).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
2020-12-20 02:04:30.322  INFO 289321 --- [           main] d.s.b.c.e.WelcomeLogoApplicationListener : 

 :: Dubbo Spring Boot (v2.7.7) : https://github.com/apache/dubbo-spring-boot-project
 :: Dubbo (v2.7.7) : https://github.com/apache/dubbo
 :: Discuss group : dev@dubbo.apache.org

2020-12-20 02:04:30.326  INFO 289321 --- [           main] e.OverrideDubboConfigApplicationListener : Dubbo Config was overridden by externalized configuration {dubbo.application.name=dubbo-registry-zookeeper-provider-sample, dubbo.application.qos-enable=false, dubbo.config-center.timeout=10000, dubbo.config.multiple=true, dubbo.protocol.name=dubbo, dubbo.protocol.port=-1, dubbo.registry.address=zookeeper://127.0.0.1:2181, dubbo.registry.file=./dubbo-cache/dubbo-registry-zookeeper-provider-sample/dubbo.cache, dubbo.scan.base-packages=org.apache.dubbo.spring.boot.sample.provider.service}

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.3.0.RELEASE)

2020-12-20 02:04:30.382  INFO 289321 --- [           main] .DubboRegistryZooKeeperProviderBootstrap : Starting DubboRegistryZooKeeperProviderBootstrap on fy-ubuntu with PID 289321 (/home/fy/workspaces/dubbo/dubbo-spring-boot-project/dubbo-spring-boot-samples/registry-samples/zookeeper-samples/provider-sample/target/classes started by fy in /home/fy/workspaces/dubbo)
2020-12-20 02:04:30.383  INFO 289321 --- [           main] .DubboRegistryZooKeeperProviderBootstrap : No active profile set, falling back to default profiles: default
2020-12-20 02:04:30.401  INFO 289321 --- [           main] com.alibaba.spring.util.BeanRegistrar    : The Infrastructure bean definition [Root bean: class [org.apache.dubbo.spring.boot.beans.factory.config.DubboConfigBeanCustomizer]; scope=; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=nullwith name [namePropertyDefaultValueDubboConfigBeanCustomizer] has been registered.
2020-12-20 02:04:30.537  INFO 289321 --- [           main] .b.f.a.ConfigurationBeanBindingRegistrar : The configuration bean definition [name : org.apache.dubbo.config.ApplicationConfig#0, content : Root bean: class [org.apache.dubbo.config.ApplicationConfig]; scope=; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null] has been registered.
2020-12-20 02:04:30.537  INFO 289321 --- [           main] com.alibaba.spring.util.BeanRegistrar    : The Infrastructure bean definition [Root bean: class [com.alibaba.spring.beans.factory.annotation.ConfigurationBeanBindingPostProcessor]; scope=; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=nullwith name [configurationBeanBindingPostProcessor] has been registered.
2020-12-20 02:04:30.537  INFO 289321 --- [           main] .b.f.a.ConfigurationBeanBindingRegistrar : The configuration bean definition [name : org.apache.dubbo.config.RegistryConfig#0, content : Root bean: class [org.apache.dubbo.config.RegistryConfig]; scope=; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null] has been registered.
2020-12-20 02:04:30.537  INFO 289321 --- [           main] .b.f.a.ConfigurationBeanBindingRegistrar : The configuration bean definition [name : org.apache.dubbo.config.ProtocolConfig#0, content : Root bean: class [org.apache.dubbo.config.ProtocolConfig]; scope=; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null] has been registered.
2020-12-20 02:04:30.537  INFO 289321 --- [           main] .b.f.a.ConfigurationBeanBindingRegistrar : The configuration bean definition [name : org.apache.dubbo.config.spring.ConfigCenterBean#0, content : Root bean: class [org.apache.dubbo.config.spring.ConfigCenterBean]; scope=; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null] has been registered.
2020-12-20 02:04:30.586  INFO 289321 --- [           main] o.s.c.a.ConfigurationClassPostProcessor  : Cannot enhance @Configuration bean definition 'org.apache.dubbo.spring.boot.autoconfigure.DubboRelaxedBinding2AutoConfiguration' since its singleton instance has been created too early. The typical cause is a non-static @Bean method with a BeanDefinitionRegistryPostProcessor return type: Consider declaring such methods as 'static'.
2020-12-20 02:04:30.586  INFO 289321 --- [           main] o.s.c.a.ConfigurationClassPostProcessor  : Cannot enhance @Configuration bean definition 'org.apache.dubbo.spring.boot.autoconfigure.DubboAutoConfiguration' since its singleton instance has been created too early. The typical cause is a non-static @Bean method with a BeanDefinitionRegistryPostProcessor return type: Consider declaring such methods as 'static'.
2020-12-20 02:04:30.669  INFO 289321 --- [           main] .a.ConfigurationBeanBindingPostProcessor : The configuration bean [<dubbo:application name="dubbo-registry-zookeeper-provider-sample" qosEnable="false" hostname="fy-ubuntu" />] have been binding by the configuration properties [{name=dubbo-registry-zookeeper-provider-sample, qos-enable=false}]
2020-12-20 02:04:30.691  INFO 289321 --- [           main] .a.ConfigurationBeanBindingPostProcessor : The configuration bean [<dubbo:registry address="zookeeper://127.0.0.1:2181" port="2181" protocol="zookeeper" file="./dubbo-cache/dubbo-registry-zookeeper-provider-sample/dubbo.cache" />] have been binding by the configuration properties [{address=zookeeper://127.0.0.1:2181, file=./dubbo-cache/dubbo-registry-zookeeper-provider-sample/dubbo.cache}]
2020-12-20 02:04:30.701  INFO 289321 --- [           main] .a.ConfigurationBeanBindingPostProcessor : The configuration bean [<dubbo:protocol name="dubbo" port="-1" />] have been binding by the configuration properties [{name=dubbo, port=-1}]
2020-12-20 02:04:30.708  INFO 289321 --- [           main] .a.ConfigurationBeanBindingPostProcessor : The configuration bean [<dubbo:config-center includeSpringEnv="false" />] have been binding by the configuration properties [{timeout=10000}]
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by javassist.ClassPool (file:/home/fy/.m2/repository/org/javassist/javassist/3.20.0-GA/javassist-3.20.0-GA.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of javassist.ClassPool
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2020-12-20 02:04:31.280  INFO 289321 --- [           main] org.apache.curator.utils.Compatibility   : Running in ZooKeeper 3.4.x compatibility mode
2020-12-20 02:04:31.292  INFO 289321 --- [           main] o.a.c.f.imps.CuratorFrameworkImpl        : Starting
2020-12-20 02:04:31.294  INFO 289321 --- [           main] org.apache.zookeeper.ZooKeeper           : Client environment:zookeeper.version=3.4.13-2d71af4dbe22557fda74f9a9b4309b15a7487f03, built on 06/29/2018 00:39 GMT
2020-12-20 02:04:31.294  INFO 289321 --- [           main] org.apache.zookeeper.ZooKeeper           : Client environment:host.name=fy-ubuntu
2020-12-20 02:04:31.294  INFO 289321 --- [           main] org.apache.zookeeper.ZooKeeper           : Client environment:java.version=15
2020-12-20 02:04:31.294  INFO 289321 --- [           main] org.apache.zookeeper.ZooKeeper           : Client environment:java.vendor=Private Build
2020-12-20 02:04:31.294  INFO 289321 --- [           main] org.apache.zookeeper.ZooKeeper           : Client environment:java.home=/usr/lib/jvm/java-15-openjdk-amd64
2020-12-20 02:04:31.294  INFO 289321 --- [           main] org.apache.zookeeper.ZooKeeper           : Client environment:java.class.path=/home/fy/workspaces/dubbo/dubbo-spring-boot-project/dubbo-spring-boot-samples/registry-samples/zookeeper-samples/provider-sample/target/classes:/home/fy/.m2/repository/org/springframework/boot/spring-boot-starter/2.3.0.RELEASE/spring-boot-starter-2.3.0.RELEASE.jar:/home/fy/.m2/repository/org/springframework/boot/spring-boot/2.3.0.RELEASE/spring-boot-2.3.0.RELEASE.jar:/home/fy/.m2/repository/org/springframework/spring-context/5.2.6.RELEASE/spring-context-5.2.6.RELEASE.jar:/home/fy/.m2/repository/org/springframework/spring-aop/5.2.6.RELEASE/spring-aop-5.2.6.RELEASE.jar:/home/fy/.m2/repository/org/springframework/spring-beans/5.2.6.RELEASE/spring-beans-5.2.6.RELEASE.jar:/home/fy/.m2/repository/org/springframework/spring-expression/5.2.6.RELEASE/spring-expression-5.2.6.RELEASE.jar:/home/fy/.m2/repository/org/springframework/boot/spring-boot-autoconfigure/2.3.0.RELEASE/spring-boot-autoconfigure-2.3.0.RELEASE.jar:/home/fy/.m2/repository/org/springframework/boot/spring-boot-starter-logging/2.3.0.RELEASE/spring-boot-starter-logging-2.3.0.RELEASE.jar:/home/fy/.m2/repository/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar:/home/fy/.m2/repository/ch/qos/logback/logback-core/1.2.3/logback-core-1.2.3.jar:/home/fy/.m2/repository/org/apache/logging/log4j/log4j-to-slf4j/2.13.2/log4j-to-slf4j-2.13.2.jar:/home/fy/.m2/repository/org/apache/logging/log4j/log4j-api/2.13.2/log4j-api-2.13.2.jar:/home/fy/.m2/repository/org/slf4j/jul-to-slf4j/1.7.30/jul-to-slf4j-1.7.30.jar:/home/fy/.m2/repository/jakarta/annotation/jakarta.annotation-api/1.3.5/jakarta.annotation-api-1.3.5.jar:/home/fy/.m2/repository/org/springframework/spring-core/5.2.6.RELEASE/spring-core-5.2.6.RELEASE.jar:/home/fy/.m2/repository/org/springframework/spring-jcl/5.2.6.RELEASE/spring-jcl-5.2.6.RELEASE.jar:/home/fy/.m2/repository/org/yaml/snakeyaml/1.26/snakeyaml-1.26.jar:/home/fy/workspaces/dubbo/dubbo-spring-boot-project/dubbo-spring-boot-starter/target/classes:/home/fy/workspaces/dubbo/dubbo-spring-boot-project/dubbo-spring-boot-autoconfigure/target/classes:/home/fy/workspaces/dubbo/dubbo-spring-boot-project/dubbo-spring-boot-compatible/autoconfigure/target/classes:/home/fy/.m2/repository/org/apache/dubbo/dubbo/2.7.7/dubbo-2.7.7.jar:/home/fy/.m2/repository/com/alibaba/spring/spring-context-support/1.0.6/spring-context-support-1.0.6.jar:/home/fy/.m2/repository/org/javassist/javassist/3.20.0-GA/javassist-3.20.0-GA.jar:/home/fy/.m2/repository/io/netty/netty-all/4.1.49.Final/netty-all-4.1.49.Final.jar:/home/fy/.m2/repository/com/google/code/gson/gson/2.8.6/gson-2.8.6.jar:/home/fy/workspaces/dubbo/dubbo-spring-boot-project/dubbo-spring-boot-samples/sample-api/target/classes:/home/fy/.m2/repository/org/apache/curator/curator-recipes/4.0.1/curator-recipes-4.0.1.jar:/home/fy/.m2/repository/org/apache/curator/curator-framework/4.0.1/curator-framework-4.0.1.jar:/home/fy/.m2/repository/org/apache/curator/curator-client/4.0.1/curator-client-4.0.1.jar:/home/fy/.m2/repository/com/google/guava/guava/20.0/guava-20.0.jar:/home/fy/.m2/repository/org/apache/zookeeper/zookeeper/3.4.13/zookeeper-3.4.13.jar:/home/fy/.m2/repository/org/slf4j/slf4j-api/1.7.30/slf4j-api-1.7.30.jar:/home/fy/.m2/repository/log4j/log4j/1.2.16/log4j-1.2.16.jar:/home/fy/.m2/repository/jline/jline/0.9.94/jline-0.9.94.jar:/home/fy/.m2/repository/org/apache/yetus/audience-annotations/0.5.0/audience-annotations-0.5.0.jar
2020-12-20 02:04:31.294  INFO 289321 --- [           main] org.apache.zookeeper.ZooKeeper           : Client environment:java.library.path=/usr/java/packages/lib:/usr/lib/x86_64-linux-gnu/jni:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/jni:/lib:/usr/lib
2020-12-20 02:04:31.294  INFO 289321 --- [           main] org.apache.zookeeper.ZooKeeper           : Client environment:java.io.tmpdir=/tmp
2020-12-20 02:04:31.294  INFO 289321 --- [           main] org.apache.zookeeper.ZooKeeper           : Client environment:java.compiler=<NA>
2020-12-20 02:04:31.294  INFO 289321 --- [           main] org.apache.zookeeper.ZooKeeper           : Client environment:os.name=Linux
2020-12-20 02:04:31.295  INFO 289321 --- [           main] org.apache.zookeeper.ZooKeeper           : Client environment:os.arch=amd64
2020-12-20 02:04:31.295  INFO 289321 --- [           main] org.apache.zookeeper.ZooKeeper           : Client environment:os.version=5.8.0-33-generic
2020-12-20 02:04:31.295  INFO 289321 --- [           main] org.apache.zookeeper.ZooKeeper           : Client environment:user.name=fy
2020-12-20 02:04:31.295  INFO 289321 --- [           main] org.apache.zookeeper.ZooKeeper           : Client environment:user.home=/home/fy
2020-12-20 02:04:31.295  INFO 289321 --- [           main] org.apache.zookeeper.ZooKeeper           : Client environment:user.dir=/home/fy/workspaces/dubbo
2020-12-20 02:04:31.295  INFO 289321 --- [           main] org.apache.zookeeper.ZooKeeper           : Initiating client connection, connectString=127.0.0.1:2181 sessionTimeout=60000 watcher=org.apache.curator.ConnectionState@1702830d
2020-12-20 02:04:31.300  INFO 289321 --- [127.0.0.1:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 127.0.0.1/<unresolved>:2181. Will not attempt to authenticate using SASL (unknown error)
2020-12-20 02:04:31.301  INFO 289321 --- [           main] o.a.c.f.imps.CuratorFrameworkImpl        : Default schema
2020-12-20 02:04:31.303  WARN 289321 --- [127.0.0.1:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x0 for server 127.0.0.1/<unresolved>:2181, unexpected error, closing socket connection and attempting reconnect

java.nio.channels.UnresolvedAddressException: null
        at java.base/sun.nio.ch.Net.checkAddress(Net.java:149) ~[na:na]
        at java.base/sun.nio.ch.Net.checkAddress(Net.java:157) ~[na:na]
        at java.base/sun.nio.ch.SocketChannelImpl.checkRemote(SocketChannelImpl.java:753) ~[na:na]
        at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:774) ~[na:na]
        at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.13.jar:3.4.13-2d71af4dbe22557fda74f9a9b4309b15a7487f03]
        at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.13.jar:3.4.13-2d71af4dbe22557fda74f9a9b4309b15a7487f03]
        at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1021) ~[zookeeper-3.4.13.jar:3.4.13-2d71af4dbe22557fda74f9a9b4309b15a7487f03]
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1064) ~[zookeeper-3.4.13.jar:3.4.13-2d71af4dbe22557fda74f9a9b4309b15a7487f03]

2020-12-20 02:04:32.405  INFO 289321 --- [127.0.0.1:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 127.0.0.1/<unresolved>:2181. Will not attempt to authenticate using SASL (unknown error)
2020-12-20 02:04:32.407  WARN 289321 --- [127.0.0.1:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x0 for server 127.0.0.1/<unresolved>:2181, unexpected error, closing socket connection and attempting reconnect

java.nio.channels.UnresolvedAddressException: null
        at java.base/sun.nio.ch.Net.checkAddress(Net.java:149) ~[na:na]
        at java.base/sun.nio.ch.Net.checkAddress(Net.java:157) ~[na:na]
        at java.base/sun.nio.ch.SocketChannelImpl.checkRemote(SocketChannelImpl.java:753) ~[na:na]
        at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:774) ~[na:na]
        at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.13.jar:3.4.13-2d71af4dbe22557fda74f9a9b4309b15a7487f03]
        at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.13.jar:3.4.13-2d71af4dbe22557fda74f9a9b4309b15a7487f03]
        at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1021) ~[zookeeper-3.4.13.jar:3.4.13-2d71af4dbe22557fda74f9a9b4309b15a7487f03]
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1064) ~[zookeeper-3.4.13.jar:3.4.13-2d71af4dbe22557fda74f9a9b4309b15a7487f03]

2020-12-20 02:04:33.508  INFO 289321 --- [127.0.0.1:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 127.0.0.1/<unresolved>:2181. Will not attempt to authenticate using SASL (unknown error)
2020-12-20 02:04:33.509  WARN 289321 --- [127.0.0.1:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x0 for server 127.0.0.1/<unresolved>:2181, unexpected error, closing socket connection and attempting reconnect

java.nio.channels.UnresolvedAddressException: null
        at java.base/sun.nio.ch.Net.checkAddress(Net.java:149) ~[na:na]
        at java.base/sun.nio.ch.Net.checkAddress(Net.java:157) ~[na:na]
        at java.base/sun.nio.ch.SocketChannelImpl.checkRemote(SocketChannelImpl.java:753) ~[na:na]
        at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:774) ~[na:na]
        at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.13.jar:3.4.13-2d71af4dbe22557fda74f9a9b4309b15a7487f03]
        at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.13.jar:3.4.13-2d71af4dbe22557fda74f9a9b4309b15a7487f03]
        at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1021) ~[zookeeper-3.4.13.jar:3.4.13-2d71af4dbe22557fda74f9a9b4309b15a7487f03]
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1064) ~[zookeeper-3.4.13.jar:3.4.13-2d71af4dbe22557fda74f9a9b4309b15a7487f03]

^C2020-12-20 02:04:34.610  INFO 289321 --- [127.0.0.1:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 127.0.0.1/<unresolved>:2181. Will not attempt to authenticate using SASL (unknown error)
2020-12-20 02:04:34.611  WARN 289321 --- [127.0.0.1:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x0 for server 127.0.0.1/<unresolved>:2181, unexpected error, closing socket connection and attempting reconnect

java.nio.channels.UnresolvedAddressException: null
        at java.base/sun.nio.ch.Net.checkAddress(Net.java:149) ~[na:na]
        at java.base/sun.nio.ch.Net.checkAddress(Net.java:157) ~[na:na]
        at java.base/sun.nio.ch.SocketChannelImpl.checkRemote(SocketChannelImpl.java:753) ~[na:na]
        at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:774) ~[na:na]
        at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.13.jar:3.4.13-2d71af4dbe22557fda74f9a9b4309b15a7487f03]
        at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.13.jar:3.4.13-2d71af4dbe22557fda74f9a9b4309b15a7487f03]
        at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1021) ~[zookeeper-3.4.13.jar:3.4.13-2d71af4dbe22557fda74f9a9b4309b15a7487f03]
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1064) ~[zookeeper-3.4.13.jar:3.4.13-2d71af4dbe22557fda74f9a9b4309b15a7487f03]

2020-12-20 02:04:35.713  INFO 289321 --- [127.0.0.1:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 127.0.0.1/<unresolved>:2181. Will not attempt to authenticate using SASL (unknown error)
2020-12-20 02:04:35.714  WARN 289321 --- [127.0.0.1:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x0 for server 127.0.0.1/<unresolved>:2181, unexpected error, closing socket connection and attempting reconnect

java.nio.channels.UnresolvedAddressException: null
        at java.base/sun.nio.ch.Net.checkAddress(Net.java:149) ~[na:na]
        at java.base/sun.nio.ch.Net.checkAddress(Net.java:157) ~[na:na]
        at java.base/sun.nio.ch.SocketChannelImpl.checkRemote(SocketChannelImpl.java:753) ~[na:na]
        at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:774) ~[na:na]
        at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277) ~[zookeeper-3.4.13.jar:3.4.13-2d71af4dbe22557fda74f9a9b4309b15a7487f03]
        at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287) ~[zookeeper-3.4.13.jar:3.4.13-2d71af4dbe22557fda74f9a9b4309b15a7487f03]
        at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1021) ~[zookeeper-3.4.13.jar:3.4.13-2d71af4dbe22557fda74f9a9b4309b15a7487f03]
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1064) ~[zookeeper-3.4.13.jar:3.4.13-2d71af4dbe22557fda74f9a9b4309b15a7487f03]

^C2020-12-20 02:04:36.309  INFO 289321 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2020-12-20 02:04:36.310  INFO 289321 --- [extShutdownHook] .b.c.e.AwaitingNonWebApplicationListener :  [Dubbo] Current Spring Boot Application is about to shutdown...
2020-12-20 02:04:36.313  INFO 289321 --- [extShutdownHook] f.a.ReferenceAnnotationBeanPostProcessor : class org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor was destroying!
2020-12-20 02:04:36.315 ERROR 289321 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: zookeeper not connected
        at org.apache.dubbo.remoting.zookeeper.curator.CuratorZookeeperClient.<init>(CuratorZookeeperClient.java:83) ~[dubbo-2.7.7.jar:2.7.7]
        at org.apache.dubbo.remoting.zookeeper.curator.CuratorZookeeperTransporter.createZookeeperClient(CuratorZookeeperTransporter.java:26) ~[dubbo-2.7.7.jar:2.7.7]
        at org.apache.dubbo.remoting.zookeeper.support.AbstractZookeeperTransporter.connect(AbstractZookeeperTransporter.java:70) ~[dubbo-2.7.7.jar:2.7.7]
        at org.apache.dubbo.remoting.zookeeper.ZookeeperTransporter$Adaptive.connect(ZookeeperTransporter$Adaptive.java) ~[dubbo-2.7.7.jar:2.7.7]
        at org.apache.dubbo.registry.zookeeper.ZookeeperRegistry.<init>(ZookeeperRegistry.java:86) ~[dubbo-2.7.7.jar:2.7.7]
        at org.apache.dubbo.registry.zookeeper.ZookeeperRegistryFactory.createRegistry(ZookeeperRegistryFactory.java:42) ~[dubbo-2.7.7.jar:2.7.7]
        at org.apache.dubbo.registry.support.AbstractRegistryFactory.getRegistry(AbstractRegistryFactory.java:122) ~[dubbo-2.7.7.jar:2.7.7]
        at org.apache.dubbo.registry.RegistryFactoryWrapper.getRegistry(RegistryFactoryWrapper.java:34) ~[dubbo-2.7.7.jar:2.7.7]
        at org.apache.dubbo.registry.RegistryFactory$Adaptive.getRegistry(RegistryFactory$Adaptive.java) ~[dubbo-2.7.7.jar:2.7.7]
        at org.apache.dubbo.registry.integration.RegistryProtocol.getRegistry(RegistryProtocol.java:357) ~[dubbo-2.7.7.jar:2.7.7]
        at org.apache.dubbo.registry.integration.RegistryProtocol.export(RegistryProtocol.java:212) ~[dubbo-2.7.7.jar:2.7.7]
        at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper.export(ProtocolFilterWrapper.java:151) ~[dubbo-2.7.7.jar:2.7.7]
        at org.apache.dubbo.qos.protocol.QosProtocolWrapper.export(QosProtocolWrapper.java:64) ~[dubbo-2.7.7.jar:2.7.7]
        at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.export(ProtocolListenerWrapper.java:60) ~[dubbo-2.7.7.jar:2.7.7]
        at org.apache.dubbo.rpc.Protocol$Adaptive.export(Protocol$Adaptive.java) ~[dubbo-2.7.7.jar:2.7.7]
        at org.apache.dubbo.config.ServiceConfig.doExportUrlsFor1Protocol(ServiceConfig.java:492) ~[dubbo-2.7.7.jar:2.7.7]
        at org.apache.dubbo.config.ServiceConfig.doExportUrls(ServiceConfig.java:325) ~[dubbo-2.7.7.jar:2.7.7]
        at org.apache.dubbo.config.ServiceConfig.doExport(ServiceConfig.java:300) ~[dubbo-2.7.7.jar:2.7.7]
        at org.apache.dubbo.config.ServiceConfig.export(ServiceConfig.java:206) ~[dubbo-2.7.7.jar:2.7.7]
        at org.apache.dubbo.config.bootstrap.DubboBootstrap.lambda$exportServices$16(DubboBootstrap.java:943) ~[dubbo-2.7.7.jar:2.7.7]
        at java.base/java.util.HashMap$Values.forEach(HashMap.java:1067) ~[na:na]
        at org.apache.dubbo.config.bootstrap.DubboBootstrap.exportServices(DubboBootstrap.java:930) ~[dubbo-2.7.7.jar:2.7.7]
        at org.apache.dubbo.config.bootstrap.DubboBootstrap.start(DubboBootstrap.java:749) ~[dubbo-2.7.7.jar:2.7.7]
        at org.apache.dubbo.config.spring.context.DubboBootstrapApplicationListener.onContextRefreshedEvent(DubboBootstrapApplicationListener.java:59) ~[dubbo-2.7.7.jar:2.7.7]
        at org.apache.dubbo.config.spring.context.DubboBootstrapApplicationListener.onApplicationContextEvent(DubboBootstrapApplicationListener.java:52) ~[dubbo-2.7.7.jar:2.7.7]
        at org.apache.dubbo.config.spring.context.OneTimeExecutionApplicationContextEventListener.onApplicationEvent(OneTimeExecutionApplicationContextEventListener.java:40) ~[dubbo-2.7.7.jar:2.7.7]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-5.2.6.RELEASE.jar:5.2.6.RELEASE]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-5.2.6.RELEASE.jar:5.2.6.RELEASE]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-5.2.6.RELEASE.jar:5.2.6.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:403) ~[spring-context-5.2.6.RELEASE.jar:5.2.6.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:360) ~[spring-context-5.2.6.RELEASE.jar:5.2.6.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:897) ~[spring-context-5.2.6.RELEASE.jar:5.2.6.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:553) ~[spring-context-5.2.6.RELEASE.jar:5.2.6.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758) ~[spring-boot-2.3.0.RELEASE.jar:2.3.0.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750) ~[spring-boot-2.3.0.RELEASE.jar:2.3.0.RELEASE]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) ~[spring-boot-2.3.0.RELEASE.jar:2.3.0.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-2.3.0.RELEASE.jar:2.3.0.RELEASE]
        at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:140) ~[spring-boot-2.3.0.RELEASE.jar:2.3.0.RELEASE]
        at org.apache.dubbo.spring.boot.sample.provider.bootstrap.DubboRegistryZooKeeperProviderBootstrap.main(DubboRegistryZooKeeperProviderBootstrap.java:34) ~[classes/:na]
Caused by: java.lang.IllegalStateException: zookeeper not connected
        at org.apache.dubbo.remoting.zookeeper.curator.CuratorZookeeperClient.<init>(CuratorZookeeperClient.java:80) ~[dubbo-2.7.7.jar:2.7.7]
        ... 38 common frames omitted

？？，确定经过测试了？有些报错也驴唇不对马嘴，让人一头雾水。。。。这东西还在维护吗？怎么看待和spring cloud的关系？
我记得海尔11年酒开始用这个dubbo，越用越垃圾，好像早就放弃dubbo了。。。。

**Comment by felixyin** [comment]
以上几个？，帮忙解决一下，谢谢。

**Comment by tech-jum** [comment]
curator的版本和zookeeper的版本不匹配的问题
