### ISSUE TITLE
graalvm initializer error

### ISSUE THREAD

**Issue by fastkdm** [apache/dubbo-spring-boot-project#819]
I use dubbo initializer to create graalvm project, compile error
### something error log:

```
[INFO] Executing: /Library/Java/JavaVirtualMachines/graalvm-ce-java17-22.3.1/Contents/Home/bin/native-image -cp /Users/Wheat Liu/IdeaProjects/demo/target/classes:/Users/Wheat Liu/.m2/repository/org/apache/dubbo/dubbo-rpc-injvm/3.3.0-beta.1/dubbo-rpc-injvm-3.3.0-beta.1.jar:/Users/Wheat Liu/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar:/Users/Wheat Liu/.m2/repository/org/apache/dubbo/dubbo-tracing/3.3.0-beta.1/dubbo-tracing-3.3.0-beta.1.jar:/Users/Wheat Liu/.m2/repository/org/apache/curator/curator-recipes/4.3.0/curator-recipes-4.3.0.jar:/Users/Wheat Liu/.m2/repository/io/netty/netty-codec-socks/4.1.94.Final/netty-codec-socks-4.1.94.Final.jar:/Users/Wheat Liu/.m2/repository/org/apache/logging/log4j/log4j-to-slf4j/2.20.0/log4j-to-slf4j-2.20.0.jar:/Users/Wheat Liu/.m2/repository/org/apache/dubbo/dubbo-remoting-api/3.3.0-beta.1/dubbo-remoting-api-3.3.0-beta.1.jar:/Users/Wheat Liu/.m2/repository/org/apache/dubbo/dubbo-config-spring/3.3.0-beta.1/dubbo-config-spring-3.3.0-beta.1.jar:/Users/Wheat Liu/.m2/repository/io/netty/netty-codec-smtp/4.1.94.Final/netty-codec-smtp-4.1.94.Final.jar:/Users/Wheat Liu/.m2/repository/io/netty/netty-transport/4.1.94.Final/netty-transport-4.1.94.Final.jar:/Users/Wheat Liu/.m2/repository/org/apache/curator/curator-framework/4.3.0/curator-framework-4.3.0.jar:/Users/Wheat Liu/.m2/repository/io/micrometer/micrometer-observation/1.11.2/micrometer-observation-1.11.2.jar:/Users/Wheat Liu/.m2/repository/org/apache/dubbo/dubbo-common/3.3.0-beta.1/dubbo-common-3.3.0-beta.1.jar:/Users/Wheat Liu/.m2/repository/org/apache/dubbo/dubbo-cluster/3.3.0-beta.1/dubbo-cluster-3.3.0-beta.1.jar:/Users/Wheat Liu/.m2/repository/io/netty/netty-transport-rxtx/4.1.94.Final/netty-transport-rxtx-4.1.94.Final.jar:/Users/Wheat Liu/.m2/repository/org/codehaus/mojo/animal-sniffer-annotations/1.17/animal-sniffer-annotations-1.17.jar:/Users/Wheat Liu/.m2/repository/javax/annotation/javax.annotation-api/1.3.2/javax.annotation-api-1.3.2.jar:/Users/Wheat Liu/.m2/repository/org/apache/dubbo/dubbo-metrics-metadata/3.3.0-beta.1/dubbo-metrics-metadata-3.3.0-beta.1.jar:/Users/Wheat Liu/.m2/repository/io/netty/netty-all/4.1.94.Final/netty-all-4.1.94.Final.jar:/Users/Wheat Liu/.m2/repository/org/springframework/spring-expression/6.0.11/spring-expression-6.0.11.jar:/Users/Wheat Liu/.m2/repository/org/apache/dubbo/dubbo-metrics-config-center/3.3.0-beta.1/dubbo-metrics-config-center-3.3.0-beta.1.jar:/Users/Wheat Liu/.m2/repository/io/netty/netty-handler/4.1.94.Final/netty-handler-4.1.94.Final.jar:/Users/Wheat Liu/.m2/repository/org/javassist/javassist/3.29.2-GA/javassist-3.29.2-GA.jar:/Users/Wheat Liu/.m2/repository/org/apache/dubbo/dubbo-serialization-api/3.3.0-beta.1/dubbo-serialization-api-3.3.0-beta.1.jar:/Users/Wheat Liu/.m2/repository/io/netty/netty-resolver-dns/4.1.94.Final/netty-resolver-dns-4.1.94.Final.jar:/Users/Wheat Liu/.m2/repository/org/checkerframework/checker-qual/2.5.2/checker-qual-2.5.2.jar:/Users/Wheat Liu/.m2/repository/io/netty/netty-codec-memcache/4.1.94.Final/netty-codec-memcache-4.1.94.Final.jar:/Users/Wheat Liu/.m2/repository/org/springframework/spring-aop/6.0.11/spring-aop-6.0.11.jar:/Users/Wheat Liu/.m2/repository/io/netty/netty-transport-native-epoll/4.1.94.Final/netty-transport-native-epoll-4.1.94.Final-linux-x86_64.jar:/Users/Wheat Liu/.m2/repository/org/apache/dubbo/dubbo/3.3.0-beta.1/dubbo-3.3.0-beta.1.jar:/Users/Wheat Liu/.m2/repository/io/netty/netty-common/4.1.94.Final/netty-common-4.1.94.Final.jar:/Users/Wheat Liu/.m2/repository/io/netty/netty-codec-http/4.1.94.Final/netty-codec-http-4.1.94.Final.jar:/Users/Wheat Liu/.m2/repository/org/apache/curator/curator-x-discovery/4.3.0/curator-x-discovery-4.3.0.jar:/Users/Wheat Liu/.m2/repository/com/google/errorprone/error_prone_annotations/2.2.0/error_prone_annotations-2.2.0.jar:/Users/Wheat Liu/.m2/repository/com/github/spotbugs/spotbugs-annotations/3.1.9/spotbugs-annotations-3.1.9.jar:/Users/Wheat Liu/.m2/repository/jline/jline/0.9.94/jline-0.9.94.jar:/Users/Wheat Liu/.m2/repository/org/apache/dubbo/dubbo-metrics-default/3.3.0-beta.1/dubbo-metrics-default-3.3.0-beta.1.jar:/Users/Wheat Liu/.m2/repository/io/micrometer/micrometer-commons/1.11.2/micrometer-commons-1.11.2.jar:/Users/Wheat Liu/.m2/repository/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar:/Users/Wheat Liu/.m2/repository/org/springframework/boot/spring-boot-starter/3.1.2/spring-boot-starter-3.1.2.jar:/Users/Wheat Liu/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.15.2/jackson-core-2.15.2.jar:/Users/Wheat Liu/.m2/repository/org/springframework/spring-context/6.0.11/spring-context-6.0.11.jar:/Users/Wheat Liu/.m2/repository/io/netty/netty-transport-native-kqueue/4.1.94.Final/netty-transport-native-kqueue-4.1.94.Final-osx-aarch_64.jar:/Users/Wheat Liu/.m2/repository/io/netty/netty-transport-classes-epoll/4.1.94.Final/netty-transport-classes-epoll-4.1.94.Final.jar:/Users/Wheat Liu/.m2/repository/io/netty/netty-codec-xml/4.1.94.Final/netty-codec-xml-4.1.94.Final.jar:/Users/Wheat Liu/.m2/repository/org/springframework/spring-beans/6.0.11/spring-beans-6.0.11.jar:/Users/Wheat Liu/.m2/repository/org/apache/dubbo/dubbo-zookeeper-spring-boot-starter/3.3.0-beta.1/dubbo-zookeeper-spring-boot-starter-3.3.0-beta.1.jar:/Users/Wheat Liu/.m2/repository/org/apache/dubbo/dubbo-spring-boot-starter/3.3.0-beta.1/dubbo-spring-boot-starter-3.3.0-beta.1.jar:/Users/Wheat Liu/.m2/repository/io/netty/netty-codec-redis/4.1.94.Final/netty-codec-redis-4.1.94.Final.jar:/Users/Wheat Liu/.m2/repository/org/apache/dubbo/dubbo-metrics-event/3.3.0-beta.1/dubbo-metrics-event-3.3.0-beta.1.jar:/Users/Wheat Liu/.m2/repository/io/netty/netty-transport-sctp/4.1.94.Final/netty-transport-sctp-4.1.94.Final.jar:/Users/Wheat Liu/.m2/repository/com/tdunning/t-digest/3.3/t-digest-3.3.jar:/Users/Wheat Liu/.m2/repository/org/apache/dubbo/dubbo-config-api/3.3.0-beta.1/dubbo-config-api-3.3.0-beta.1.jar:/Users/Wheat Liu/.m2/repository/org/apache/dubbo/dubbo-metrics-registry/3.3.0-beta.1/dubbo-metrics-registry-3.3.0-beta.1.jar:/Users/Wheat Liu/.m2/repository/org/apache/curator/curator-client/4.3.0/curator-client-4.3.0.jar:/Users/Wheat Liu/.m2/repository/io/netty/netty-resolver-dns-native-macos/4.1.94.Final/netty-resolver-dns-native-macos-4.1.94.Final-osx-x86_64.jar:/Users/Wheat Liu/.m2/repository/org/springframework/spring-core/6.0.11/spring-core-6.0.11.jar:/Users/Wheat Liu/.m2/repository/org/apache/logging/log4j/log4j-api/2.20.0/log4j-api-2.20.0.jar:/Users/Wheat Liu/.m2/repository/org/yaml/snakeyaml/1.33/snakeyaml-1.33.jar:/Users/Wheat Liu/.m2/repository/com/alibaba/fastjson2/fastjson2/2.0.40/fastjson2-2.0.40.jar:/Users/Wheat Liu/.m2/repository/log4j/log4j/1.2.17/log4j-1.2.17.jar:/Users/Wheat Liu/.m2/repository/io/micrometer/context-propagation/1.0.4/context-propagation-1.0.4.jar:/Users/Wheat Liu/.m2/repository/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar:/Users/Wheat Liu/.m2/repository/org/apache/dubbo/dubbo-monitor-api/3.3.0-beta.1/dubbo-monitor-api-3.3.0-beta.1.jar:/Users/Wheat Liu/.m2/repository/io/netty/netty-transport-udt/4.1.94.Final/netty-transport-udt-4.1.94.Final.jar:/Users/Wheat Liu/.m2/repository/org/apache/dubbo/dubbo-registry-api/3.3.0-beta.1/dubbo-registry-api-3.3.0-beta.1.jar:/Users/Wheat Liu/.m2/repository/io/micrometer/micrometer-core/1.11.2/micrometer-core-1.11.2.jar:/Users/Wheat Liu/.m2/repository/io/netty/netty-handler-ssl-ocsp/4.1.94.Final/netty-handler-ssl-ocsp-4.1.94.Final.jar:/Users/Wheat Liu/.m2/repository/io/netty/netty-codec-haproxy/4.1.94.Final/netty-codec-haproxy-4.1.94.Final.jar:/Users/Wheat Liu/.m2/repository/org/slf4j/jul-to-slf4j/2.0.7/jul-to-slf4j-2.0.7.jar:/Users/Wheat Liu/.m2/repository/org/apache/dubbo/dubbo-rpc-api/3.3.0-beta.1/dubbo-rpc-api-3.3.0-beta.1.jar:/Users/Wheat Liu/.m2/repository/org/apache/zookeeper/zookeeper/3.4.14/zookeeper-3.4.14.jar:/Users/Wheat Liu/.m2/repository/org/springframework/boot/spring-boot/3.1.2/spring-boot-3.1.2.jar:/Users/Wheat Liu/.m2/repository/io/netty/netty-codec/4.1.94.Final/netty-codec-4.1.94.Final.jar:/Users/Wheat Liu/.m2/repository/org/apache/dubbo/dubbo-metadata-api/3.3.0-beta.1/dubbo-metadata-api-3.3.0-beta.1.jar:/Users/Wheat Liu/.m2/repository/io/micrometer/micrometer-tracing/1.1.3/micrometer-tracing-1.1.3.jar:/Users/Wheat Liu/.m2/repository/org/apache/yetus/audience-annotations/0.5.0/audience-annotations-0.5.0.jar:/Users/Wheat Liu/.m2/repository/ch/qos/logback/logback-classic/1.4.8/logback-classic-1.4.8.jar:/Users/Wheat Liu/.m2/repository/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar:/Users/Wheat Liu/.m2/repository/io/netty/netty-codec-http2/4.1.94.Final/netty-codec-http2-4.1.94.Final.jar:/Users/Wheat Liu/.m2/repository/org/springframework/boot/spring-boot-autoconfigure/3.1.2/spring-boot-autoconfigure-3.1.2.jar:/Users/Wheat Liu/.m2/repository/io/netty/netty-resolver-dns-native-macos/4.1.94.Final/netty-resolver-dns-native-macos-4.1.94.Final-osx-aarch_64.jar:/Users/Wheat Liu/.m2/repository/org/apache/dubbo/dubbo-spring-boot-autoconfigure-compatible/3.3.0-beta.1/dubbo-spring-boot-autoconfigure-compatible-3.3.0-beta.1.jar:/Users/Wheat Liu/.m2/repository/org/springframework/boot/spring-boot-starter-logging/3.1.2/spring-boot-starter-logging-3.1.2.jar:/Users/Wheat Liu/.m2/repository/io/netty/netty-buffer/4.1.94.Final/netty-buffer-4.1.94.Final.jar:/Users/Wheat Liu/.m2/repository/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar:/Users/Wheat Liu/.m2/repository/org/springframework/spring-web/6.0.11/spring-web-6.0.11.jar:/Users/Wheat Liu/.m2/repository/io/netty/netty-resolver-dns-classes-macos/4.1.94.Final/netty-resolver-dns-classes-macos-4.1.94.Final.jar:/Users/Wheat Liu/.m2/repository/org/slf4j/slf4j-api/2.0.7/slf4j-api-2.0.7.jar:/Users/Wheat Liu/.m2/repository/org/springframework/spring-jcl/6.0.11/spring-jcl-6.0.11.jar:/Users/Wheat Liu/.m2/repository/io/netty/netty-transport-classes-kqueue/4.1.94.Final/netty-transport-classes-kqueue-4.1.94.Final.jar:/Users/Wheat Liu/.m2/repository/org/apache/dubbo/dubbo-metrics-api/3.3.0-beta.1/dubbo-metrics-api-3.3.0-beta.1.jar:/Users/Wheat Liu/.m2/repository/com/google/j2objc/j2objc-annotations/1.1/j2objc-annotations-1.1.jar:/Users/Wheat Liu/.m2/repository/org/apache/dubbo/dubbo-container-api/3.3.0-beta.1/dubbo-container-api-3.3.0-beta.1.jar:/Users/Wheat Liu/.m2/repository/org/apache/dubbo/dubbo-spring-boot-autoconfigure/3.3.0-beta.1/dubbo-spring-boot-autoconfigure-3.3.0-beta.1.jar:/Users/Wheat Liu/.m2/repository/jakarta/annotation/jakarta.annotation-api/2.1.1/jakarta.annotation-api-2.1.1.jar:/Users/Wheat Liu/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.15.2/jackson-annotations-2.15.2.jar:/Users/Wheat Liu/.m2/repository/io/netty/netty-transport-native-epoll/4.1.94.Final/netty-transport-native-epoll-4.1.94.Final-linux-aarch_64.jar:/Users/Wheat Liu/.m2/repository/org/apache/dubbo/dubbo-native/3.3.0-beta.1/dubbo-native-3.3.0-beta.1.jar:/Users/Wheat Liu/.m2/repository/io/netty/netty-transport-native-kqueue/4.1.94.Final/netty-transport-native-kqueue-4.1.94.Final-osx-x86_64.jar:/Users/Wheat Liu/.m2/repository/ch/qos/logback/logback-core/1.4.8/logback-core-1.4.8.jar:/Users/Wheat Liu/.m2/repository/io/netty/netty-codec-dns/4.1.94.Final/netty-codec-dns-4.1.94.Final.jar:/Users/Wheat Liu/.m2/repository/org/apache/dubbo/dubbo-config-spring6/3.3.0-beta.1/dubbo-config-spring6-3.3.0-beta.1.jar:/Users/Wheat Liu/.m2/repository/com/alibaba/spring/spring-context-support/1.0.11/spring-context-support-1.0.11.jar:/Users/Wheat Liu/.m2/repository/com/alibaba/hessian-lite/3.2.13/hessian-lite-3.2.13.jar:/Users/Wheat Liu/.m2/repository/com/google/guava/guava/27.0.1-jre/guava-27.0.1-jre.jar:/Users/Wheat Liu/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.15.2/jackson-databind-2.15.2.jar:/Users/Wheat Liu/.m2/repository/org/latencyutils/LatencyUtils/2.0.3/LatencyUtils-2.0.3.jar:/Users/Wheat Liu/.m2/repository/org/hdrhistogram/HdrHistogram/2.1.12/HdrHistogram-2.1.12.jar:/Users/Wheat Liu/.m2/repository/io/netty/netty-handler-proxy/4.1.94.Final/netty-handler-proxy-4.1.94.Final.jar:/Users/Wheat Liu/.m2/repository/io/netty/netty-resolver/4.1.94.Final/netty-resolver-4.1.94.Final.jar:/Users/Wheat Liu/.m2/repository/io/netty/netty-codec-mqtt/4.1.94.Final/netty-codec-mqtt-4.1.94.Final.jar:/Users/Wheat Liu/.m2/repository/io/netty/netty-transport-native-unix-common/4.1.94.Final/netty-transport-native-unix-common-4.1.94.Final.jar:/Users/Wheat Liu/.m2/repository/io/netty/netty-codec-stomp/4.1.94.Final/netty-codec-stomp-4.1.94.Final.jar:/Users/Wheat Liu/.m2/repository/org/slf4j/slf4j-reload4j/2.0.7/slf4j-reload4j-2.0.7.jar --no-fallback -H:Path=/Users/Wheat Liu/IdeaProjects/demo/target -H:Name=demo -H:ConfigurationFileDirectories=/Users/Wheat Liu/IdeaProjects/demo/target/graalvm-reachability-metadata/33eb26dc9127b8dae41bff4c01374222b1b1e7e7/io.netty/netty-common/4.1.80.Final,/Users/Wheat Liu/IdeaProjects/demo/target/graalvm-reachability-metadata/33eb26dc9127b8dae41bff4c01374222b1b1e7e7/org.hdrhistogram/HdrHistogram/2.1.12,/Users/Wheat Liu/IdeaProjects/demo/target/graalvm-reachability-metadata/33eb26dc9127b8dae41bff4c01374222b1b1e7e7/ch.qos.logback/logback-classic/1.4.1,/Users/Wheat Liu/IdeaProjects/demo/target/graalvm-reachability-metadata/33eb26dc9127b8dae41bff4c01374222b1b1e7e7/io.netty/netty-resolver-dns/4.1.80.Final,/Users/Wheat Liu/IdeaProjects/demo/target/graalvm-reachability-metadata/33eb26dc9127b8dae41bff4c01374222b1b1e7e7/io.netty/netty-buffer/4.1.80.Final,/Users/Wheat Liu/IdeaProjects/demo/target/graalvm-reachability-metadata/33eb26dc9127b8dae41bff4c01374222b1b1e7e7/io.netty/netty-codec-http2/4.1.80.Final,/Users/Wheat Liu/IdeaProjects/demo/target/graalvm-reachability-metadata/33eb26dc9127b8dae41bff4c01374222b1b1e7e7/io.netty/netty-handler/4.1.80.Final,/Users/Wheat Liu/IdeaProjects/demo/target/graalvm-reachability-metadata/33eb26dc9127b8dae41bff4c01374222b1b1e7e7/io.netty/netty-transport/4.1.80.Final,/Users/Wheat Liu/IdeaProjects/demo/target/graalvm-reachability-metadata/33eb26dc9127b8dae41bff4c01374222b1b1e7e7/io.netty/netty-codec-http/4.1.80.Final --exclude-config \Q/Users/Wheat Liu/.m2/repository/io/netty/netty-transport/4.1.94.Final/netty-transport-4.1.94.Final.jar\E ^/META-INF/native-image/ --exclude-config \Q/Users/Wheat Liu/.m2/repository/io/netty/netty-handler/4.1.94.Final/netty-handler-4.1.94.Final.jar\E ^/META-INF/native-image/ --exclude-config \Q/Users/Wheat Liu/.m2/repository/io/netty/netty-resolver-dns/4.1.94.Final/netty-resolver-dns-4.1.94.Final.jar\E ^/META-INF/native-image/ --exclude-config \Q/Users/Wheat Liu/.m2/repository/io/netty/netty-common/4.1.94.Final/netty-common-4.1.94.Final.jar\E ^/META-INF/native-image/ --exclude-config \Q/Users/Wheat Liu/.m2/repository/io/netty/netty-codec-http/4.1.94.Final/netty-codec-http-4.1.94.Final.jar\E ^/META-INF/native-image/ --exclude-config \Q/Users/Wheat Liu/.m2/repository/io/netty/netty-codec-http2/4.1.94.Final/netty-codec-http2-4.1.94.Final.jar\E ^/META-INF/native-image/ --exclude-config \Q/Users/Wheat Liu/.m2/repository/io/netty/netty-buffer/4.1.94.Final/netty-buffer-4.1.94.Final.jar\E ^/META-INF/native-image/
Exception in thread "main" java.util.regex.PatternSyntaxException: Illegal/unsupported escape sequence near index 90
Liu/.m2/repository/io/netty/netty-transport/4.1.94.Final/netty-transport-4.1.94.Final.jar\E
                                                                                          ^
	at java.base@17.0.6/java.util.regex.Pattern.error(Pattern.java:2028)
	at java.base@17.0.6/java.util.regex.Pattern.escape(Pattern.java:2608)
	at java.base@17.0.6/java.util.regex.Pattern.atom(Pattern.java:2286)
	at java.base@17.0.6/java.util.regex.Pattern.sequence(Pattern.java:2210)
	at java.base@17.0.6/java.util.regex.Pattern.expr(Pattern.java:2069)
	at java.base@17.0.6/java.util.regex.Pattern.compile(Pattern.java:1783)
	at java.base@17.0.6/java.util.regex.Pattern.<init>(Pattern.java:1430)
	at java.base@17.0.6/java.util.regex.Pattern.compile(Pattern.java:1069)
	at org.graalvm.nativeimage.driver/com.oracle.svm.driver.CmdLineOptionHandler.consume(CmdLineOptionHandler.java:124)
	at org.graalvm.nativeimage.driver/com.oracle.svm.driver.CmdLineOptionHandler.consume(CmdLineOptionHandler.java:59)
	at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage$NativeImageArgsProcessor.apply(NativeImage.java:1499)
	at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.processNativeImageArgs(NativeImage.java:1770)
	at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.completeImageBuild(NativeImage.java:959)
	at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.build(NativeImage.java:1417)
	at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1387)
	at org.graalvm.nativeimage.driver/com.oracle.svm.driver.NativeImage.main(NativeImage.java:1374)
```
### maven pom:
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.wheat.cloud</groupId>
    <artifactId>demo</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>demo</name>
    <description>demo</description>
    <properties>
        <java.version>17</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <dubbo.version>3.3.0-beta.1</dubbo.version>
        <spring-boot.version>3.1.2</spring-boot.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-config-spring6</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-native</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-spring-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-zookeeper-spring-boot-starter</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.apache.dubbo</groupId>
                <artifactId>dubbo-bom</artifactId>
                <version>${dubbo.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <source>17</source>
                    <target>17</target>
                    <encoding>UTF-8</encoding>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>${spring-boot.version}</version>
                <configuration>
                    <mainClass>com.example.demo.DemoApplication</mainClass>
                </configuration>
                <executions>
                    <execution>
                        <id>repackage</id>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>native</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.springframework.boot</groupId>
                        <artifactId>spring-boot-maven-plugin</artifactId>
                        <version>${spring-boot.version}</version>
                        <configuration>
                            <mainClass>com.example.demo.DemoApplication</mainClass>
                        </configuration>
                        <executions>
                            <execution>
                                <id>process-aot</id>
                                <goals>
                                    <goal>process-aot</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.graalvm.buildtools</groupId>
                        <artifactId>native-maven-plugin</artifactId>
                        <version>0.9.20</version>
                        <configuration>
                            <classDirectory>${project.build.outputDirectory}</classDirectory>
                            <metadataRepository>
                                <enabled>true</enabled>
                            </metadataRepository>
                        </configuration>
                        <executions>
                            <execution>
                                <id>add-reachability-metadata</id>
                                <goals>
                                    <goal>add-reachability-metadata</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.dubbo</groupId>
                        <artifactId>dubbo-maven-plugin</artifactId>
                        <version>${dubbo.version}</version>
                        <configuration>
                            <mainClass>com.example.demo.DemoApplication</mainClass>
                        </configuration>
                        <executions>
                            <execution>
                                <id>dubbo-process-aot</id>
                                <phase>process-sources</phase>
                                <goals>
                                    <goal>dubbo-process-aot</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>

</project>
```

i guess the error may be related this:
dubbo-spring-boot-starter import netty,and use metadata error

or may be my mistake?

**Comment by CrazyHZM** [comment]
@fastkdm 
The contents of this repo have been moved to https://github.com/apache/dubbo. For native cases, refer to https://github.com/apache/dubbo-samples/tree/master/2-advanced/dubbo-samples-native-image-registry.
